### ISSUE TITLE
AppEnginServerConfigurationTypeTest.testIsApplicable_notAppEngineStandardApp appeared to flake

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-intellij#1267]
https://cloud-tools-for-java-testing.appspot.com/job/google-cloud-intellij%20CI%20Build%20%28IDEA%202016%29/1089/testReport/junit/com.google.cloud.tools.intellij.appengine.run/AppEngineServerConfigurationTypeTest/testIsApplicable_notAppEngineStandardApp/

Saw this for https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1264 and https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1262

Failed, and then succeeded after an update.  It's possible the merge fixed it..

```
com.google.cloud.tools.intellij.appengine.run.AppEngineServerConfigurationTypeTest.testIsApplicable_notAppEngineStandardApp

Failing for the past 1 build (Since Failed#1089 )
Took 29 sec.
add description
Error Message

junit.framework.AssertionFailedError
Stacktrace

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertNotNull(Assert.java:220)
	at junit.framework.Assert.assertNotNull(Assert.java:213)
	at com.intellij.testFramework.PlatformTestCase.doCreateRealModuleIn(PlatformTestCase.java:341)
	at com.intellij.testFramework.PlatformTestCase.doCreateRealModule(PlatformTestCase.java:336)
	at com.intellij.testFramework.PlatformTestCase.createModule(PlatformTestCase.java:332)
	at com.intellij.testFramework.PlatformTestCase.createMainModule(PlatformTestCase.java:328)
	at com.intellij.testFramework.PlatformTestCase$1.run(PlatformTestCase.java:322)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:182)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:109)
	at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:157)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:160)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:104)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
	at com.intellij.testFramework.PlatformTestCase.setUpModule(PlatformTestCase.java:324)
	at com.intellij.testFramework.PlatformTestCase.setUpProject(PlatformTestCase.java:232)
	at com.intellij.testFramework.PlatformTestCase.setUp(PlatformTestCase.java:196)
	at com.google.cloud.tools.intellij.appengine.run.AppEngineServerConfigurationTypeTest.setUp(AppEngineServerConfigurationTypeTest.java:44)
	at com.intellij.testFramework.PlatformTestCase.b(PlatformTestCase.java:646)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:28)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:26)
	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$b0f40f3d.run(EdtTestUtil.kt)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by etanshaul** [comment]
closed as stale
