### ISSUE TITLE
User report: CloudSdk missing java sdk validation exeption

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#1602]
Description
Invalid Java SDK. D:\IntelliJ IDEA 2017.2\jre64\bin\java.exe does not exist.
Stack trace:
com.google.cloud.tools.appengine.cloudsdk.InvalidJavaSdkException: Invalid Java SDK. D:\IntelliJ IDEA 2017.2\jre64\bin\java.exe does not exist.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateJdk(CloudSdk.java:495)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateCloudSdk(CloudSdk.java:458)
	at com.google.cloud.tools.intellij.appengine.sdk.DefaultCloudSdkService.validateCloudSdk(DefaultCloudSdkService.java:113)
	at com.google.cloud.tools.intellij.appengine.sdk.CloudSdkService.validateCloudSdk(CloudSdkService.java:53)
	at com.google.cloud.tools.intellij.appengine.sdk.DefaultCloudSdkVersionNotifier.notifyIfUnsupportedVersion(DefaultCloudSdkVersionNotifier.java:33)
	at com.google.cloud.tools.intellij.startup.CloudSdkVersionStartupCheck.runActivity(CloudSdkVersionStartupCheck.java:35)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:176)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:162)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:367)
	at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:182)
	at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:296)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.b(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)

**Comment by etanshaul** [comment]
closed as stale / no long seen
