### ISSUE TITLE
User reported exception: java.util.MissingFormatArgumentException: Format specifier '%s'

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2232]
Stack trace:
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.google.cloud.tools.intellij.stackdriver.debugger.BreakpointUtil.getUserMessage(BreakpointUtil.java:52)
	at com.google.cloud.tools.intellij.stackdriver.debugger.CloudStackFrame$MyValue.computePresentation(CloudStackFrame.java:169)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:58)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.lambda$addChildren$0(XValueContainerNode.java:98)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:104)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:101)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception class name:
java.util.MissingFormatArgumentException
Exception message:
Format specifier '%s'
Throw file name:
Formatter.java
Throw line number:
2519
Throw class name:
java.util.Formatter
Throw method name:
format
Submitted on:
August 09, 2018 09:49 (Time)
August 09, 2018 06:49 (PDT)
Product Version:
2018.1.3
Country:
CA

**Comment by sageprice** [comment]
Not fully sure what happened here, do we have any information about what was happening when we got this report?

At any rate, from the [FormatString#getFormat documentation](https://developers.google.com/resources/api-libraries/documentation/clouddebugger/v2/java/latest/com/google/api/services/clouddebugger/v2/model/FormatMessage.html#getFormat--):
```
Format template for the message. The `format` uses placeholders `$0`, `$1`, etc. to reference parameters. `$$` can be used to denote the `$` character. Examples: * `Failed to load '$0' which helps debug $1 the first time it is loaded. Again, $0 is very important.` * `Please pay $$10 to use $0 instead of $1.`
```

The code prior to where the error is thrown does a simple substitution of `$x` in the input string, incrementing x from 0 to whatever. Without knowing what an input string looks like, we can imagine a few potential issues:

1. There's a `$$` in the input format which we are not substituting properly. In the worst case this looks like `$$10` --> `$10` and we erroneously transform into `$%s0`, adding an extra `%s`
1. If there are double-digit parameters (is this possible?) then we could erroneously be transforming `$10` into `%s0` (this would just produce noise in the error, not cause a failure)
1. If the status message contains a `%s` prior to any of our substitutions, then when we call `String.format` there will be an extra format specifier

(1) and (3) could actually cause the error we see here. I'll send out a small fix which tries to address these, then returns null if the number of format specifiers does not add up properly.

**Comment by sageprice** [comment]
Nvm, realized we're passing the params as a `List` when `String.format` requires `Object...`. So the list is always processed as a single element, and we see the above exception whenever there are multiple parameters. Fixing this, then may follow up with cases noted above.
