### ISSUE TITLE
NPE at AppEngineServerModel reported by user

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2239]
java.lang.NullPointerException at AppEngineServerModel.getServices : null
Description
null
Stack trace:
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.instance.AppEngineServerModel.getServices(AppEngineServerModel.java:209)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.run(CloudSdkAppEngineDevServer1.java:70)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:79)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:161)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:76)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception class name:
java.lang.NullPointerException
Exception message:
null
Throw file name:
AppEngineServerModel.java
Throw line number:
209
Throw class name:
com.google.cloud.tools.intellij.appengine.java.ultimate.server.instance.AppEngineServerModel
Throw method name:
getServices
Submitted on:
August 17, 2018 13:39 (Time)
August 17, 2018 10:39 (PDT)
Product Version:
2018.1.6

**Comment by etanshaul** [comment]
@ivanporty assigned to you if you have a moment to investigate
