### ISSUE TITLE
User reported error: invalid JDK

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2291]
```
com.google.cloud.tools.appengine.cloudsdk.InvalidJavaSdkException: Invalid Java SDK ..java.exe does not exist

at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateJdk(CloudSdk.java:224)
	at com.google.cloud.tools.appengine.cloudsdk.DevAppServerRunner.runV1(DevAppServerRunner.java:110)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.run(CloudSdkAppEngineDevServer1.java:153)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:103)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartu
```

plugin v 18.10.1
idea 2017.3.5

**Comment by etanshaul** [comment]
outdated, no longer seen
