### ISSUE TITLE
User reported: Duplicate key AppEngineGradleModule IllegalStateException

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2310]
```
java.lang.IllegalStateException at Collectors.lambda$throwingMerger$0 : Duplicate key com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleModule@3121a97d
Stack trace:
java.lang.IllegalStateException: Duplicate key com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleModule@3121a97d
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleProjectDataService.collectByModuleName(AppEngineGradleProjectDataService.java:
```

IDEA 2018.3.1
plugin 18.12.1

**Comment by etanshaul** [comment]
dup of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2660
