### ISSUE TITLE
com.google.cloud.tools.appengine.cloudsdk.InvalidJavaSdkException: Invalid Java SDK. 

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2327]
```
Stack trace:
com.google.cloud.tools.appengine.cloudsdk.InvalidJavaSdkException: Invalid Java SDK. ***/bin/java does not exist.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdk.validateJdk(CloudSdk.java:224)
	at com.google.cloud.tools.appengine.cloudsdk.AppCfgRunner.run(AppCfgRunner.java:54)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineStandardStaging.stageStandard(CloudSdkAppEngineStandardStaging.java:83)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardStage.stage(AppEngineStandardStage.java:81)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardDeployTask.execute(AppEngineStandardDeployTask.java:99)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)

```

app.name.version
 IntelliJ IDEA
app.version.major
 2018
app.version.minor
 2.6
java.version
 1.8.0_152-release
java.vm.vendor
 JetBrains s.r.o
os.name
 Linux
plugin.version
 19.1.2

**Comment by ivanporty** [comment]
This probably shouldn't be surfaced as a fatal plugin error exception.

**Comment by etanshaul** [comment]
closing as stale; there have been a lot of sdk changes since this
