### ISSUE TITLE
User reported: AppEngineException: org.xml.sax.SAXParseException thrown at IDE level

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2333]
```
Stack trace:
com.google.cloud.tools.appengine.api.AppEngineException: org.xml.sax.SAXParseException; lineNumber: 17; columnNumber: 6; The content of elements must consist of well-formed character data or markup.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:225)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.run(CloudSdkAppEngineDevServer1.java:114)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:103)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:176)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:89)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 17; columnNumber: 6; The content of elements must consist of well-formed character data or markup.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.google.cloud.tools.appengine.AppEngineDescriptor.parse(AppEngineDescriptor.java:59)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:219)
	... 16 more
```

app.name.version
 IntelliJ IDEA
app.version.major
 2018
app.version.minor
 3.4
java.version
 1.8.0_152-release
java.vm.vendor
 JetBrains s.r.o
os.name
 Linux
plugin.version
 19.1.2

**Comment by jmah-cc** [comment]
We haven't seen this issue recently. Please re-open if you're still able to repro it
