### ISSUE TITLE
User reported: java.lang.LinkageError at ClassLoader.defineClass1 : loader constraint violation

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2405]
```
java.lang.LinkageError at ClassLoader.defineClass1 : loader constraint violation: loader (instance of com/intellij/util/lang/UrlClassLoader) previously initiated loading for a different type with name "org/apache/http/client/CredentialsProvider"
Stack trace:
java.lang.LinkageError: loader constraint violation: loader (instance of com/intellij/util/lang/UrlClassLoader) previously initiated loading for a different type with name "org/apache/http/client/CredentialsProvider"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
```

plugin version 19.2.1
IDEA 2018.3.5

**Comment by jmah-cc** [comment]
We haven't seen this issue recently. Please re-open if you're still able to repro it
