### ISSUE TITLE
Assertion error in CSR GcpHttpAuthDataProvider

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2468]
```
java.lang.AssertionError
	at com.google.cloud.tools.intellij.csr.GcpHttpAuthDataProvider$Context.create(GcpHttpAuthDataProvider.java:177)
	at com.google.cloud.tools.intellij.csr.GcpHttpAuthDataProvider.createContext(GcpHttpAuthDataProvider.java:120)
	at com.google.cloud.tools.intellij.csr.GcpCheckoutProvider$1.run(GcpCheckoutProvider.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)

```

plugin version 19.2.1
IDEA 2018.3.4

**Comment by jmah-cc** [comment]
We haven't seen this issue recently. Please re-open if you're still able to repro it
