### ISSUE TITLE
User reported: `PluginException: Short name not matched for class com.google.cloud.tools.intellij.appengine.java.validation.ConstructorInspection`

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2474]
```
com.intellij.diagnostic.PluginException: Short name not matched for class com.google.cloud.tools.intellij.appengine.java.validation.ConstructorInspection: getShortName() = ***; ep.shortName = #Constructor [Plugin: com.google.gct.core]
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:709)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPassFactory$MyLocalInspectionsPass.getInspectionTools(LocalInspectionsPassFactory.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
```

plugin version 19.3.1
IDEA 2019.1

**Comment by matthewmichihara** [comment]
If the short name returned at https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/blob/master/app-engine/java/src/com/google/cloud/tools/intellij/appengine/java/validation/ConstructorInspection.java#L56 does not match `Constructor`, an error is logged in the `com.intellij.codeInspection.ex.InspectionToolWrapper#getTool` method.

AFAICT, `Constructor` should always be returned there because we don't have translations for any plugin strings in https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/blob/master/app-engine/java/resources/messages/EndpointBundle.properties#L30.

I could see this error occurring if somehow translations were injected into the plugin.

**Comment by sageprice** [comment]
Got another report for this with 19.5.3 (exact same stack trace) so I'm trying to catch up -- what do we want to do here? Would adding translations somehow help? Is this something we're actually going to work on?

**Comment by matthewmichihara** [comment]
I'm voting we close this as won't fix. We're assuming this is due to some non-standard way of adding translations to IntelliJ that we can't really do anything about.

@etanshaul

**Comment by etanshaul** [comment]
yeah. lets do that. if the user happens about this issue by google searching, then we can re-open and try to address.

**Comment by fsladkey** [comment]
Adding another slightly different stack trace here to help with debugging if this becomes something we want to tackle.

```
com.intellij.diagnostic.PluginException: Short name not matched for class com.google.cloud.tools.intellij.appengine.java.validation.ConstructorInspection: getShortName() = #コンストラクター; ep.shortName = #Constructor [Plugin: com.google.gct.core]
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:73)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getStaticDescription(InspectionToolWrapper.java:157)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.loadDescription(InspectionToolWrapper.java:161)
	at com.intellij.codeInspection.ex.InspectionSearchableOptionContributor.processOptions(InspectionSearchableOptionContributor.java:44)
	at com.intellij.ide.ui.search.SearchableOptionPreloader.preload(SearchableOptionPreloader.java:49)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
