### ISSUE TITLE
2019.1: IllegalArgumentException in GcsBucketPanel

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2491]
User reported.
```
java.lang.IllegalArgumentException: Wrong end: 1; document length=0; start=1
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:74)
	at com.intellij.openapi.editor.impl.RangeMarkerImpl.<init>(RangeMarkerImpl.java:57)
	at com.intellij.openapi.editor.impl.DocumentImpl.createRangeMarkerForVirtualFile(DocumentImpl.java:219)
	at com.intellij.openapi.editor.impl.LazyRangeMarkerFactoryImpl.lambda$createRangeMarker$0(LazyRangeMarkerFactoryImpl.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:970)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.editor.impl.LazyRangeMarkerFactoryImpl.createRangeMarker(LazyRangeMarkerFactoryImpl.java:38)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.<init>(OpenFileDescriptor.java:78)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.<init>(OpenFileDescriptor.java:56)
	at com.google.cloud.tools.intellij.gcs.GcsBucketPanel.loadBucketContents(GcsBucketPanel.java:227)
	at com.google.cloud.tools.intellij.gcs.GcsBucketPanel.access$200(GcsBucketPanel.java:56)
	at com.google.cloud.tools.intellij.gcs.GcsBucketPanel$1.mouseClicked(GcsBucketPanel.java:90)
```

PyCharm 2019.1
os.name
 Linux
plugin.version
 19.3.1

**Comment by sageprice** [comment]
Got another report for this in 19.7.1. Going to look into it a bit now.

**Comment by sageprice** [comment]
Seems like it is being thrown pretty internally, but it is triggered by us passing an `offset` value equal to 1 when we create an `OpenFileDescriptor`.

It's still unclear to me what offset is supposed to do, perhaps indicate cursor start location on the opened file? At any rate, looking way down it seems like offset must be >= 0 and less than document length. Not sure what the document in question here is, but it can apparently have length 0. If we pass 0 instead of 1 we'll stop seeing this error, but I don't know if there is a real issue here with some malformed or improperly configured file.

Since I don't know how to replicate the scenario which got us here, I'm inclined to just decrement `offset` and wait until someone files an issue with more information about how to get into this state so we can fix the underlying problem.
