### ISSUE TITLE
User reported: UI builder exception with 2018.2.7 in KubernetesSettings panel

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2498]
```
Stack trace:
java.lang.NoSuchMethodError: com.intellij.ui.layout.LayoutBuilder.noteRow$default(Lcom/intellij/ui/layout/LayoutBuilder;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)V
	at com.google.kubernetes.tools.settings.KubernetesSettingsConfigurable.createComponent(KubernetesSettingsConfigurable.kt:84)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:163)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$0(ConfigurableCardPanel.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:69)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:55)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:58)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:55)
```

app.name.version
 IntelliJ IDEA
app.version.major
 2018
app.version.minor
 2.7
java.version
 1.8.0_152-release
java.vm.vendor
 JetBrains s.r.o
os.name
 Mac OS X
plugin.version
 19.4.1

**Comment by Luxas98** [comment]
Getting same one on the linux ```com.intellij.ui.layout.LayoutBuilder.noteRow$default(Lcom/intellij/ui/layout/LayoutBuilder;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)V 
java.lang.NoSuchMethodError: com.intellij.ui.layout.LayoutBuilder.noteRow$default(Lcom/intellij/ui/layout/LayoutBuilder;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)V
	at com.google.kubernetes.tools.settings.KubernetesSettingsConfigurable.createComponent(KubernetesSettingsConfigurable.kt:84)```

PyCharm 2018.2.3  Build #PY-182.4323.49 
JDK: 1.8.0_152-release 
VM: OpenJDK 64-Bit Server VM 
Vendor: JetBrains s.r.o 
OS: Linux

**Comment by etanshaul** [comment]
@Luxas98 sorry you are running in to this. Do you still get this even after restarting the IDE?

**Comment by ivanporty** [comment]
Closing as UI builder is not stable and it was replaced with standard layout methods/forms.
