### ISSUE TITLE
User reported exception: IllegalStateException at ProjectUtil.guessProjectDir : Not applicable for default project

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2504]
```
Cluster
java.lang.IllegalStateException at ProjectUtil.guessProjectDir : Not applicable for default project
Stack trace:
java.lang.IllegalStateException: Not applicable for default project
	at com.intellij.openapi.project.ProjectUtil.guessProjectDir(ProjectUtil.kt:121)
	at com.google.kubernetes.tools.skaffold.run.ui.SkaffoldFilesComboBox.setProject(SkaffoldFilesComboBox.kt:43)
	at com.google.kubernetes.tools.skaffold.run.ui.BaseSkaffoldSettingsEditor.resetEditorFrom(BaseSkaffoldSettingsEditor.kt:125)
	at com.google.kubernetes.tools.skaffold.run.ui.SkaffoldSingleRunSettingsEditor.resetEditorFrom(SkaffoldSingleRunSettingsEditor.kt:48)
	at com.google.kubernetes.tools.skaffold.run.ui.SkaffoldSingleRunSettingsEditor.resetEditorFrom(SkaffoldSingleRunSettingsEditor.kt:28)
```

**Comment by ivanporty** [comment]
Oh interesting how they managed to use run configuration with the default project? Good to know though, needs to be fixed then.

**Comment by ivanporty** [comment]
and we assumed this one returns `null` for default projects, so this is not true it seems.

**Comment by etanshaul** [comment]
Yea it is interesting. I don't know off hand how to reproduce since a project presumably needs to be opened in order to use the run config :/

**Comment by ivanporty** [comment]
Ok so this is for project default templates. We can disable resetting from settings for this case.
