### ISSUE TITLE
User reported exception: reading Skaffold YAML file

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2523]
```
java.lang.AssertionError: Unexpected content storage modification: page=18; newRecord=18476
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findOrCreateContentRecord(FSRecords.java:1609)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$3600(FSRecords.java:47)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.lambda$writeBytes$0(FSRecords.java:1532)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:962)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$300(FSRecords.java:47)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.writeBytes(FSRecords.java:1525)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.access$3200(FSRecords.java:1506)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeContent(FSRecords.java:1471)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.writeContent(PersistentFSImpl.java:246)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.contentsToByteArray(PersistentFSImpl.java:524)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:139)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:130)
	at com.google.kubernetes.tools.skaffold.SkaffoldYamlConfiguration.<init>(SkaffoldYamlConfiguration.kt:55)
	at com.google.kubernetes.tools.skaffold.SkaffoldYamlConfiguration.<init>(SkaffoldYamlConfiguration.kt:36)
	at com.google.kubernetes.tools.skaffold.SkaffoldFileService.isSkaffoldFile(SkaffoldFileService.kt:42)
	at com.google.kubernetes.tools.skaffold.SkaffoldConfigurationDetector$projectOpened$3$checkForSkaffoldFile$1.run(SkaffoldConfigurationDetector.kt:103)

```

app.name.version
 PyCharm
app.version.major
 2019
app.version.minor
 1.1
java.version
 11.0.2
java.vm.vendor
 JetBrains s.r.o
os.name
 Windows 10
plugin.version
 19.4.1

**Comment by jmah-cc** [comment]
We haven't seen this issue recently. Please re-open if you're still able to repro it
