### ISSUE TITLE
`noteRow` used in Kotlin DSL UI builder is not available in 2018.2

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2525]
We need to either make 2018.3 the earliest supported version or stop using `noteRow` to allow support for 2018.2. However, we cannot reliably compile / build  on 2018.2 since it has some incompatible run configuration changes and can only test already built plugin, so it probably makes sense to bump up supported versions up to 2018.3

**Comment by ivanporty** [comment]
```
java.lang.NoSuchMethodError: com.intellij.ui.layout.LayoutBuilder.noteRow$default(Lcom/intellij/ui/layout/LayoutBuilder;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)V
	at com.google.kubernetes.tools.settings.KubernetesSettingsConfigurable.createComponent(KubernetesSettingsConfigurable.kt:84)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:163)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$0(ConfigurableCardPanel.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:955)
```

**Comment by etanshaul** [comment]
I'm in favor of updating our UI logic, if possible, to continue to support 2018.2. That version was released not so long ago (around August last year), and I continue to see usage of that version.

**Comment by ivanporty** [comment]
Here is the alternative:
```java
            row {
                label(helperText, 0, UIUtil.ComponentStyle.SMALL)
            }
```

**Comment by ivanporty** [comment]
I'll update and test.

**Comment by etanshaul** [comment]
thanks @ivanporty for finding that
