### ISSUE TITLE
Kubernetes context dropdown is empty

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2527]
I still need to test this out more, but for tracking - I'm getting the following:

<img width="860" alt="Screen Shot 2019-04-29 at 7 34 03 PM" src="https://user-images.githubusercontent.com/1735744/56933434-d663cb80-6ab5-11e9-876b-3a4c86c1bc08.png">

Despite having multiple contexts available:
<img width="650" alt="Screen Shot 2019-04-29 at 7 36 10 PM" src="https://user-images.githubusercontent.com/1735744/56933484-0f03a500-6ab6-11e9-93fe-370de0537372.png">

Running on a branch based off of the latest in `master`, and the plugin "normally" (installed manually from zip) and not built from gradle.

**Comment by etanshaul** [comment]
@GoogleCloudPlatform/cloud-tools-for-intellij 

Any one else noticing this?

**Comment by matthewmichihara** [comment]
Let me try reproducing it with the 'normal' plugin installation method. Does it still occur if the plugin is built from gradle?

**Comment by sageprice** [comment]
I'm unable to reproduce on either Ubuntu or Mac, with plugin built from Gradle.

**Comment by etanshaul** [comment]
Thanks for trying. I only noticed this when using the "normal" method. When building from Gradle I didn't see it. I noticed this on my Mac. Will test again on Linux

**Comment by etanshaul** [comment]
![image](https://user-images.githubusercontent.com/1735744/56975547-0c00c700-6b3f-11e9-93f4-85b7a788b647.png)

**Comment by matthewmichihara** [comment]
After installing from zip, I'm seeing the same thing. Will investigate.

1. `./gradlew buildPlugin`
2. Install from `cloud-code-intellij-internal/google-cloud-tools-plugin/build/distributions`

![image](https://user-images.githubusercontent.com/79073/56978143-d3fc8280-6b44-11e9-9243-cc14533a4ff1.png)

**Comment by etanshaul** [comment]
thanks @matthewmichihara

**Comment by matthewmichihara** [comment]
In the idea logs, we see

```
2019-04-30 12:37:46,903 [  50540]   WARN - n.ui.SkaffoldDevSettingsEditor - Could not determine the active Kubernetes context
com.intellij.execution.ExecutionException: Could not find kubectl installation on PATH: please install kubectl.
For more information on required dependencies, see https://cloud.google.com/code/docs/intellij/install#prerequisites
        at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.executeKubectlBlocking(KubectlExecutorService.kt:65)
        at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlApi.getConfig(KubectlApi.kt:114)
        at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$1.invoke(BaseSkaffoldSettingsEditor.kt:218)
        at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$1.invoke(BaseSkaffoldSettingsEditor.kt:50)
        at com.google.cloud.tools.intellij.ui.UiBackgroundJobService$runUiJobInBackground$3.invokeSuspend(UiBackgroundJobService.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

```
The current hypothesis is that this is because `KubectlExecutorService` attempts to run `kubectl` with `ProcessBuilder` and `SkaffoldExecutorService` uses `GeneralCommandLine` which includes necessary PATH fixes. I'll try to make `KubectlExecutorService` use `GeneralCommandLine`.
