### ISSUE TITLE
Notification group Google App Engine should be a singleton

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2534]
```
2019-05-02 16:53:37,422 [   7205]   INFO - notification.NotificationGroup - Notification group Google App Engine plugin is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
	at com.google.cloud.tools.intellij.appengine.java.facet.standard.AppEngineStandardSupportProvider.<clinit>(AppEngineStandardSupportProvider.java:83)
	at com.google.cloud.tools.intellij.appengine.java.facet.standard.AddAppEngineStandardFrameworkSupportToolsMenuAction.<init>(AddAppEngineStandardFrameworkSupportToolsMenuAction.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:392)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:379)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:471)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:459)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.lambda$null$0(Preloader.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.Preloader.lambda$initComponent$1(Preloader.java:63)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ivanporty** [comment]
```
2019-05-02 17:36:08,873 [  22125]   INFO - notification.NotificationGroup - Notification group Cloud Code by Google plugin is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
	at com.google.cloud.tools.intellij.kubernetes.PluginNotificationSettingsKt.<clinit>(PluginNotificationSettings.kt:33)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.CloudCodeInitAction.createNotification(CloudCodeInitAction.kt:107)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.CloudCodeInitAction.createNotification$default(CloudCodeInitAction.kt:105)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.CloudCodeInitAction.showSupportAlreadyExistsMessage(CloudCodeInitAction.kt:83)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.CloudCodeInitAction.actionPerformed(CloudCodeInitAction.kt:55)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem
```
