### ISSUE TITLE
Possible UI creation crash in JetBrains 2019.2 EAP

### ISSUE THREAD

**Issue by sageprice** [GoogleCloudPlatform/cloud-code-intellij#2605]
Partial stack trace from user error report:
```
java.lang.NoSuchMethodError: com.intellij.ui.layout.Cell.invoke$default(Lcom/intellij/ui/layout/Cell;Ljavax/swing/JComponent;[Lcom/intellij/ui/layout/CCFlags;ILcom/intellij/ui/layout/GrowPolicy;Ljava/lang/String;ILjava/lang/Object;)V
	at com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable.createComponent(KubernetesSettingsConfigurable.kt:106)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:155)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$0(ConfigurableCardPanel.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:934)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:69)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:55)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:58)
	at com.intellij.openapi.options.newEditor.ConfigurableEditor$1.create(ConfigurableEditor.java:55)
	at com.intellij.ui.CardLayoutPanel.createValue(CardLayoutPanel.java:87)
	at com.intellij.ui.CardLayoutPanel.select(CardLayoutPanel.java:115)
	at com.intellij.ui.CardLayoutPanel.lambda$null$0(CardLayoutPanel.java:131)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:782)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:731)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:396)
...
```

app.name.version:   IntelliJ IDEA
app.version.major:   2019
app.version.minor:   2
java.version:   11.0.3
java.vm.vendor:   JetBrains s.r.o
os.name:   Linux
plugin.version:   20190702

Not wholly sure what is going on here, but this error is thrown where we grow the `TextFieldWithBrowseButton` which allows users to search for a Skaffold executable in the settings configurable.

User was running the 2019.2 EAP version of IntelliJ with what I assume is the 20190702 nightly build of the plugin. It's possible there has been an API change we need to handle for 2019.2.

**Comment by etanshaul** [comment]
thanks for filing @sageprice 

@sageprice @matthewmichihara @ZariaHoward, could one of you take a look at this? This version will be leaving EAP soon and we want to make sure we support it. I added to our next milestone.

**Comment by sageprice** [comment]
I should have time to take a look today.

**Comment by sageprice** [comment]
Able to reproduce on 2019.2 EAP on Mac running nightly 20190710. Actual UX is that the settings page cannot be opened, with an indefinitely spinning "Loading" icon.

**Comment by sageprice** [comment]
Screenshot:

<img width="1341" alt="Screen Shot 2019-07-10 at 11 52 51 AM" src="https://user-images.githubusercontent.com/9577120/60984236-5b1a6380-a309-11e9-99ee-2a6681671ac3.png">

Note that the settings are stuck on the previous tab I had open, in this case "Plugins". The actual settings configurable is totally blocked.

**Comment by sageprice** [comment]
To summarize - we were using a soon-to-be deprecated API for UI construction. We've updated our code to use the supported method. Nightly builds and 19.7.1 should now not cause freezes when opening Cloud Code UI components with 2019.2.

**Comment by sageprice** [comment]
Just got a report, still seeing a similar error in nightly 20190714. I downloaded 20190715 and am also still seeing the error there. The error has changed slightly, see this line:

```
java.lang.NoSuchMethodError: com.intellij.ui.layout.Row.label$default(Lcom/intellij/ui/layout/Row;Ljava/lang/String;ILcom/intellij/util/ui/UIUtil$ComponentStyle;Lcom/intellij/util/ui/UIUtil$FontColor;ZILjava/lang/Object;)V
	at com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable.createComponent(KubernetesSettingsConfigurable.kt:106)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:155)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$0(ConfigurableCardPanel.java:74)
...
```

Possible I missed that the `label` DSL component is also going away and not just `row(label)`. Looking into this further.

**Comment by sageprice** [comment]
Hmm the previously mentioned `row` API had an annotation of `ScheduledForRemoval`, but with that gone I'm not seeing anything else marked for deprecation. Gonna have to keep looking around.

**Comment by sageprice** [comment]
Confirmed I'm going crazy. I'm running build #IU-192.5728.12 of the 2019.2 EAP, with an up-to-date  copy of master branch. Using a zip of the plugin built with `./gradlew buildPlugin` the error is not present. However, it is present with 20190715 nightly build.

There have definitely not been any changes to our plugin over the weekend, so I have to assume that the changes made previously are not in nightly. Not sure how to verify this.

**Comment by etanshaul** [comment]
can you pop open the nightly zip and check to confirm? I wonder if something is wrong with our nightly scrip.

**Comment by sageprice** [comment]
Not entirely sure what I'm doing, so apologies in advance if I missed something. I've opened both the locally-built plugin and the nightly plugin zips, and after decompiling there do appear to be some differences in `KubernetesSettingsConfigurable`. In particular, the one built locally has no reference to `Row.label$default` (see the most recent error) whereas the decompiled 20190715 does.

So there are definitely some differences. Unclear to me whether that is an issue with the nightly script or if there is something about my local configuration which would cause such a difference. At this point I probably need help from someone to repeat these checks and confirm whether the error is on my end.

**Comment by sageprice** [comment]
Ignoring my config issues for a moment, it does appear that additional Kotlin UI DSL components have been removed (or my local config is broken). In particular, the `panel` and `label` UI elements have been removed in the EAP. Still looking into what the alternatives are. I've requested more information in the plugin developers Gitter channel: https://gitter.im/IntelliJ-Plugin-Developers/Lobby?at=5d2ca7db3596f56f8ce31df4

**Comment by sageprice** [comment]
Still waiting on a response from JetBrains. At this point it seems like our best bet is to forego using the Kotlin UI DSL, and construct the UI elements using form builder or in the Java style. This isn't good, but it will at least ensure cross-version compatibility.
