### ISSUE TITLE
IllegalStateException when unable to find current K8s context

### ISSUE THREAD

**Issue by sageprice** [GoogleCloudPlatform/cloud-code-intellij#2606]
New (to me) user report. User was running plugin version 19.5.3 on IntelliJ version 2019.1.3 on Mac OS X. Stack trace:

```
java.lang.IllegalStateException: Could not find the current Kubernetes context.
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.KubernetesContextComboBox.updateModel(KubernetesContextComboBox.kt:79)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$2.invoke(BaseSkaffoldSettingsEditor.kt:241)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$2.invoke(BaseSkaffoldSettingsEditor.kt:51)
	at com.google.cloud.tools.intellij.ui.UiBackgroundJobService$runUiJobInBackground$3$1.invokeSuspend(UiBackgroundJobService.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
...
```

This error occurs when opening the run configurations editor for either Cloud Code run config (deploy or continuous deploy).

I'm pretty curious how the user got in this state, the only explanation I've been able to come up with is that the user has contexts specified elsewhere which we aren't recognizing (perhaps they have multiple kubeconfigs, which we don't yet support). But it's also worth noting that we are throwing `IllegalStateException` rather than displaying a more reasonable error to the user. The result of this error is that the combo box does not list any contexts despite some context existing.

Perhaps as a first step we should instead throw a `ConfigurationException` so the error state (contexts found, current context not among them) is displayed in the run config window itself?

**Comment by etanshaul** [comment]
@matthewmichihara mind taking a look at this? I think you updated the relevant logic at one point.

**Comment by matthewmichihara** [comment]
sure

**Comment by matthewmichihara** [comment]
@sageprice do you have a link to where this bug originated from?

**Comment by sageprice** [comment]
> @sageprice do you have a link to where this bug originated from?

From Listnr (user reported via IntelliJ): https://listnrcrash.corp.google.com/product/717949/crash/1000000000071198778?status=1,3&dateRange=30
