### ISSUE TITLE
Avoid using logger.error to report plugin exception for issues when running App Engine local server

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2613]
We use logger.error to report App Engine start up issues such as malformed XML which should be handled more gracefully.

User reported exception:
```
com.google.cloud.tools.appengine.api.AppEngineException: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 20; XML document structures must start and end within the same entity.
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:225)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.run(CloudSdkAppEngineDevServer1.java:114)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:109)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:180)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:89)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:200)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 20; XML document structures must start and end within the same entity.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.google.cloud.tools.appengine.AppEngineDescriptor.parse(AppEngineDescriptor.java:59)
	at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.isJava8(CloudSdkAppEngineDevServer1.java:219)
	... 16 more


app.name.version
 IntelliJ IDEA
app.version.major
 2018
app.version.minor
 3.6
java.version
 1.8.0_152-release
plugin.version
 19.5.3
```

**Comment by sageprice** [comment]
Out of curiosity do we know the source of the root error? Are these malformed XML files coming from users, or are we pushing something bad?

**Comment by ivanporty** [comment]
I don't think we are generating malformed XMLs, the one we do is pretty simple, but worth checking this as well of course, good thinking.

**Comment by etanshaul** [comment]
lowering priority of this as we haven't no (or close to zero) reports about this

**Comment by etanshaul** [comment]
closing as stale
