### ISSUE TITLE
User reported exception -- static initializer NoClassDefFoundError

### ISSUE THREAD

**Issue by sageprice** [GoogleCloudPlatform/cloud-code-intellij#2614]
Stack trace:

```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/JavaVersion
	at com.google.cloud.tools.intellij.appengine.java.facet.standard.AppEngineStandardFacet.<clinit>(AppEngineStandardFacet.java:38)
	at com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineForbiddenCodeInspection.checkFile(AppEngineForbiddenCodeInspection.java:64)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitFile(AbstractBaseJavaLocalInspectionTool.java:70)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:331)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:517)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.JavaVersion PluginClassLoader[com.google.gct.core, 19.7.1] com.intellij.ide.plugins.cl.PluginClassLoader@775bb4f7
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
```

Product/version data
```
app.name.version  -- IntelliJ IDEA
app.version.major -- 2019
app.version.minor -- 2
java.version      -- 1.8.0_201
java.vm.vendor    -- Oracle Corporation
os.name           -- Mac OS X
plugin.version    -- 19.7.1
```

I haven't a clue what is happening here. We initialize a map of `String` to `JavaVersion` and it looks like `JavaVersion` cannot be found at construction time. Happening in the newest release (19.7.1) running on the latest non-EAP version of IntelliJ (2019.2).

**Comment by etanshaul** [comment]
we need to get to the bottom of these `NoClassDefFoundError`s. I see them every once in a while right after a new release, and they taper off and disappear shortly after.

I wonder if its a classloading issue when a new plugin is loaded. Something we can probably ask JB on one of the chat channels.

**Comment by jmah-cc** [comment]
Was specific to an older version of the plugin. Closing as it hasn't been since in a while.
