### ISSUE TITLE
User reported: java.lang.IllegalStateException: Null context selected (in BaseSkaffoldSettingsEditor)

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2624]
```
java.lang.IllegalStateException at BaseSkaffoldSettingsEditor$createEditor$3.actionPerformed : Null context selected
Stack trace:
java.lang.IllegalStateException: Null context selected
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$createEditor$3.actionPerformed(BaseSkaffoldSettingsEditor.kt:151)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1332)
	at javax.swing.JComboBox.intervalRemoved(JComboBox.java:1352)
	at javax.swing.AbstractListModel.fireIntervalRemoved(AbstractListModel.java:179)
	at javax.swing.DefaultComboBoxModel.removeAllElements(DefaultComboBoxModel.java:174)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.KubernetesContextComboBox.updateModel(KubernetesContextComboBox.kt:66)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$2.invoke(BaseSkaffoldSettingsEditor.kt:241)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$2.invoke(BaseSkaffoldSettingsEditor.kt:51)
	at com.google.cloud.tools.intellij.ui.UiBackgroundJobService$runUiJobInBackground$3$1.invokeSuspend(UiBackgroundJobService.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
```

plugin version 19.5.3
IJ IDEA 2019.1.3

**Comment by matthewmichihara** [comment]
Fixed in 19.9.1
