### ISSUE TITLE
User reported: NPE UsersListCellRenderer.getListCellRendererComponent

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2629]
```
java.lang.NullPointerException
	at com.google.cloud.tools.intellij.login.ui.UsersListCellRenderer.getListCellRendererComponent(UsersListCellRenderer.java:129)
	at com.google.cloud.tools.intellij.login.ui.UsersListCellRenderer.getListCellRendererComponent(UsersListCellRenderer.java:53)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:167)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at com.intellij.ui.components.JBList.getPreferredSize(JBList.java:184)
	at java.desktop/javax.swing.JList.getScrollableTracksViewportWidth(JList.java:2776)
	at com.intellij.ui.components.JBScrollPane$Layout.preferredLayoutSize(JBScrollPane.java:698)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:799)
	at com.intellij.ui.popup.AbstractPopup.show(AbstractPopup.java:442)
	at com.intellij.ui.popup.AbstractPopup.showUnderneathOf(AbstractPopup.java:434)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginAction.showPopup(GoogleLoginAction.java:71)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginAction.actionPerformed(GoogleLoginAction.java:47)
```

IDEA 2019.2
Plugin 19.7.2

**Comment by etanshaul** [comment]
I don't think this was released yet last non patch release was July 30

**Comment by etanshaul** [comment]
closing since the fix was not yet released
