### ISSUE TITLE
User reported: com.google.cloud.tools.appengine.AppEngineException: org.xml.sax.SAXParseException

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2631]
```
Stack trace:
com.google.cloud.tools.appengine.AppEngineException: org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 7; The string "--" is not permitted within comments.
	at com.google.cloud.tools.appengine.operations.DevServer.isSandboxEnforced(DevServer.java:202)
	at com.google.cloud.tools.appengine.operations.DevServer.run(DevServer.java:93)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineStandardRunTask.execute(AppEngineStandardRunTask.java:110)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.CloudSdkStartupPolicy$1$1.createProcessHandler(CloudSdkStartupPolicy.java:180)
	at com.intellij.javaee.run.execution.PatchedLocalState.startJ2EEProcess(PatchedLocalState.java:92)
	at com.intellij.javaee.run.execution.J2EEProcessHandlerWrapper.lambda$new$0(J2EEProcessHandlerWrapper.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 15; columnNumber: 7; The string "--" is not permitted within comments.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.google.cloud.tools.appengine.AppEngineDescriptor.parse(AppEngineDescriptor.java:58)
	at com.google.cloud.tools.appengine.operations.DevServer.isSandboxEnforced(DevServer.java:196)
	... 16 more
```

```
app.name.version
 IntelliJ IDEA
app.version.major
 2019
app.version.minor
 1.2
java.version
 1.8.0_202-release
os.name
 Windows
plugin.version
 19.7.2
```

**Comment by etanshaul** [comment]
closing. haven't seen this in a while and it is on an old version of the plugin
