### ISSUE TITLE
User reported: CloudSdkNotFoundException: Validation Error

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2634]
```
com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkNotFoundException: Validation Error: gcloud location _ is not a file.
	at com.google.cloud.tools.appengine.operations.CloudSdk.validateCloudSdkLocation(CloudSdk.java:215)
	at com.google.cloud.tools.appengine.operations.CloudSdk.validateCloudSdk(CloudSdk.java:189)
	at com.google.cloud.tools.appengine.operations.GcloudRunner.run(GcloudRunner.java:81)
	at com.google.cloud.tools.appengine.operations.Deployment.deploy(Deployment.java:96)
	at com.google.cloud.tools.intellij.appengine.java.cloud.AppEngineDeploy.deploy(AppEngineDeploy.java:156)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineFlexibleDeployTask.execute(AppEngineFlexibleDeployTask.java:102)
	at com.google.cloud.tools.intellij.appengine.java.cloud.executor.AppEngineExecutor.run(AppEngineExecutor.java:42)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	
```

IDE version 2019.2
plugin 19.7.2

**Comment by jmah-cc** [comment]
Closing since this is on an older version of the plugin and we haven't seen this issue since.
