### ISSUE TITLE
User reported: AssertionError at AppEngineStandardStage

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2635]
```
java.lang.AssertionError
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:58)
	at com.intellij.remoteServer.impl.runtime.log.LoggingHandlerImpl$Colored.print(LoggingHandlerImpl.java:94)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardStage.lambda$stage$0(AppEngineStandardStage.java:60)
	at com.google.cloud.tools.appengine.operations.cloudsdk.process.LegacyProcessHandler$1.run(LegacyProcessHandler.java:100)
```

app.name.version
 IntelliJ IDEA
app.version.major
 2019
app.version.minor
 2
java.version
 11.0.3
java.vm.vendor
 JetBrains s.r.o
plugin.version
 19.7.2

**Comment by etanshaul** [comment]
dup of #2621
