### ISSUE TITLE
User reported: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2640]
```
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at com.google.cloud.tools.intellij.csr.RepositorySelector$RepositoryPanel.lambda$new$1(RepositorySelector.java:264)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
..
	at git4idea.DialogManager.show(DialogManager.java:23)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.uploadProjectToGoogleCloud(SetupCloudRepositoryAction.java:141)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.actionPerformed(SetupCloudRepositoryAction.java:123)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
```

app.name.version
 IntelliJ IDEA
app.version.major
 2019
app.version.minor
 1.3
java.version
 11.0.2
java.vm.vendor
 JetBrains s.r.o
os.name
 Linux
plugin.version
 19.7.2

**Comment by jmah-cc** [comment]
@ivanporty Should we close this issue now?

**Comment by ivanporty** [comment]
We can probably close as this never happened again.
