### ISSUE TITLE
Kubernetes context dropdown remains empty

### ISSUE THREAD

**Issue by gjong** [GoogleCloudPlatform/cloud-code-intellij#2644]
When trying to edit the run configuration the dialog reports the following message: 'Invalid Data: Could not determine the active Kubernetes context'

- Cloud Code for IntelliJ version: 19.7.2
- OS: Windows 10.0.18362 Build 18362

**The following message is displayed:**

![image](https://user-images.githubusercontent.com/1543130/64041639-50898700-cb60-11e9-9360-95ff924ca608.png)

**When accessing the InteliJ log file I get this error message:**
```
2019-08-30 19:54:47,583 [15758553]   WARN - n.ui.SkaffoldDevSettingsEditor - Could not determine the active Kubernetes context 
java.util.concurrent.TimeoutException: kubectl config view -o json
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.executeKubectlBlocking(KubectlExecutorService.kt:130)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.executeKubectlBlocking$default(KubectlExecutorService.kt:119)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlApi.getConfig(KubectlApi.kt:105)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.BaseSkaffoldSettingsEditor$resetKubernetesContextFrom$1$config$1.invokeSuspend(BaseSkaffoldSettingsEditor.kt:262)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

The strange thing is that I am sure that kubectl is on the PATH and correctly configured. As when I run the same command from the command prompt in Windows I get correct results.
![image](https://user-images.githubusercontent.com/1543130/64041858-cdb4fc00-cb60-11e9-8e1b-496c59da079f.png)

As well as in the docker desktop context selector:
![image](https://user-images.githubusercontent.com/1543130/64041934-0359e500-cb61-11e9-885f-6add3e4ac9ab.png)

**Comment by ivanporty** [comment]
@gjong Thank you for using Cloud Code IJ! Indeed, it seems we are using a timeout that is too restrictive in case of many configuration entries, we should allow more time to get the results and show them. We'll try fix this right away for a next upcoming release (planned for the next week).

**Comment by etanshaul** [comment]
@gjong just fyi the fix by @ivanporty will go out in our next release (scheduled for next Monday). Tentative release notes: https://github.com/GoogleCloudPlatform/cloud-code-intellij/blob/4f63925da0dc721afa571e4ac42aee4df28cab4a/CHANGELOG.md
