### ISSUE TITLE
user reported: InstallerFailedException

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2652]
```
com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerFailedException: Installer exited with non-zero status code 1: cannot retrieve skaffold.exe

	at com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerManager.executeInstaller(InstallerManager.kt:85)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerTask.run(InstallerTask.kt:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by etanshaul** [comment]
@sageprice / @ivanporty we can close this now I guess (mirrored by internal issue `843`)?

**Comment by sageprice** [comment]
Yep - currently staged changes mean we shouldn't be exposing this error to users.
