### ISSUE TITLE
Crash report: service not available in country X during login

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2658]
plugin 19.10.1
IDE 2019.1
```
com.google.api.client.http.HttpResponseException at HttpRequest.execute : 403 Forbidden This service is not available from _. If you believe the country of origin was incorrectly identified, please report it at https://support.google.com/websearch/contact/ip.
```

```
Stack trace:
com.google.api.client.http.HttpResponseException: 404 Not Found
Not Found
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.queryEmail(GoogleLoginState.java:507)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.updateUserCredentials(GoogleLoginState.java:419)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.logInWithLocalServer(GoogleLoginState.java:359)
	at com.google.cloud.tools.intellij.login.IntegratedIntellijGoogleLoginService$1.run(IntegratedIntellijGoogleLoginService.java:219)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
```

**Comment by etanshaul** [comment]
would be nice to catch this error and show the message in a useful way to the user
