### ISSUE TITLE
AppengineGradleModule duplicateKeyException

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2660]
```
java.lang.IllegalStateException: Duplicate key * (attempted merging values com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleModule@5d6c7a59 and com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleModule@3ae58fc3)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleProjectDataService.collectByModuleName(AppEngineGradleProjectDataService.java:86)
	at com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleProjectDataService.importData
```

plugin 19.10.1
Idea 2019.2.3

**Comment by sageprice** [comment]
Not sure of context, would it be correct to just de-dupe on the key and continue here?

**Comment by etanshaul** [comment]
hmm. I haven't dug into this yet, but module name should be unique, so yeah deduping on key (and logging a warning) sounds like the right thing to do.

**Comment by etanshaul** [comment]
dup of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2756
