### ISSUE TITLE
Skaffold file service read access allowed only from EDT

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2661]
PyCharm 2019.2.3
Plugin: 10/22 nightly build

```
java.lang.Throwable at Logger.error : Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Description
Details: Current thread: Thread[DefaultDispatcher-worker-4 @coroutine#5,6,Idea Thread Group] 758531155
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2019.2.3#PY-192.6817.19 PyCharm, eap:false, os:Mac OS X 10.14.6, java-version:JetBrains s.r.o 1.8.0_202-release-b1491 2019.2.3#PY-192.6817.19 PyCharm, eap:false, os:Mac OS X 10.14.6, java-version:JetBrains s.r.o 1.8.0_202-release-b1491,6,Idea Thread Group] 1340754072
Stack trace:
java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1027)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:711)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:892)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:968)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:939)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:811)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getFilesWithFileType(FileNameIndexServiceImpl.java:56)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:41)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.findSkaffoldFiles(SkaffoldFileService.kt:96)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService.canGenerateConfiguration(SkaffoldInitService.kt:80)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService$notifyUserIfGenerationPossible$1$canGenerateConfiguration$1.invokeSuspend(SkaffoldInitService.kt:147)
```

**Comment by etanshaul** [comment]
https://listnrcrash.corp.google.com/product/717949/report/1000000550192048263
