### ISSUE TITLE
KubernetesSettingsConfigurable.cancel NoSuchMethodError

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2684]
Exception report:

IDEA 2019.2.4
plugin version 19.12.1

```
java.lang.NoSuchMethodError at KubernetesSettingsConfigurable.disposeUIResources : 'void com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable.cancel()'
Stack trace:
java.lang.NoSuchMethodError: 'void com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable.cancel()'
	at com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable.disposeUIResources(KubernetesSettingsConfigurable.kt:114)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.disposeUIResources(ConfigurableWrapper.java:177)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.dispose(ConfigurableCardPanel.java:110)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.dispose(ConfigurableCardPanel.java:36)
	at com.intellij.ui.CardLayoutPanel.removeAll(CardLayoutPanel.java:195)
	at com.intellij.ui.CardLayoutPanel.dispose(CardLayoutPanel.java:71)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:47)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:43)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:135)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:124)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:194)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:104)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:124)
```

**Comment by etanshaul** [comment]
2019.3 added a `cancel` method to the base class.

The intention here though is to call `CoroutineScope#cancel`, so when the plugin is compiled against 2019.3, we get this runtime error in version 2019.2.3 of the platform.

**Comment by etanshaul** [comment]
fixed. will go out in the next release
