### ISSUE TITLE
java.lang.IllegalStateException at LanguageServerCompletionContributor$Companion.createCompletion : completionItem.insertText must not be null

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2690]
https://listnrcrash.corp.google.com/product/717949/report/1000000619444111226

```
java.lang.IllegalStateException: completionItem.insertText must not be null
	at com.google.cloud.tools.intellij.languageclient.LanguageServerCompletionContributor$Companion.createCompletion(LanguageServerCompletionContributor.kt:85)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerCompletionContributor$Companion.extractCompletions(LanguageServerCompletionContributor.kt:68)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerCompletionContributor$fillCompletionVariants$callable$1.call(LanguageServerCompletionContributor.kt:182)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerCompletionContributor$fillCompletionVariants$callable$1.call(LanguageServerCompletionContributor.kt:47)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$null$1(ApplicationUtil.java:40)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by peterlin741** [comment]
https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/1180
