### ISSUE TITLE
java.io.IOException at LocalFileSystemBase.createChildFile

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2692]
https://listnrcrash.corp.google.com/product/717949/report/1000000619544132167

It looks like the Cloud Code related part of this stack trace is --
```
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.uploadProjectToGoogleCloud(SetupCloudRepositoryAction.java:130)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.actionPerformed(SetupCloudRepositoryAction.java:124)
```

**Comment by jmah-cc** [comment]
We haven't seen this issue recently. Please re-open if you're still able to repro it
