### ISSUE TITLE
Fix various 2020 EAP runtime exceptions

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2698]
Umbrella issue to track clean up for the 2020 EAP.

Example stack trace from 2020.1 EAP using 20.1.2 (nightly build) Cloud Code:

```
java.lang.Throwable: window with id="Google Cloud Storage" isn't registered
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getRegisteredMutableInfoOrLogError(ToolWindowManagerImpl.kt:581)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.setShowStripeButton(ToolWindowManagerImpl.kt:1823)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setShowStripeButton(ToolWindowImpl.kt:426)
	at com.google.cloud.tools.intellij.gcs.GcsToolWindowFactory.init(GcsToolWindowFactory.java:44)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:922)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doInitToolWindow(ToolWindowManagerImpl.kt:468)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:429)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:89)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpened$2.run(ToolWindowManagerImpl.kt:410)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:468)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:444)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:421)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:990)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:187)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:173)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.
```

**Comment by etanshaul** [comment]
fixed
