### ISSUE TITLE
2020.1 EAP "Google Cloud Storage" isn't registered exception

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2704]
```
Cluster
java.lang.Throwable at Logger.error : window with id="Google Cloud Storage" isn't registered
Stack trace:
java.lang.Throwable: window with id="Google Cloud Storage" isn't registered
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.getRegisteredMutableInfoOrLogError(ToolWindowManagerImpl.kt:586)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.setShowStripeButton(ToolWindowManagerImpl.kt:1836)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setShowStripeButton(ToolWindowImpl.kt:428)
	at com.google.cloud.tools.intellij.gcs.GcsToolWindowFactory.init(GcsToolWindowFactory.java:44)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:930)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doInitToolWindow(ToolWindowManagerImpl.kt:469)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:430)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:90)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpened$2.run(ToolWindowManagerImpl.kt:411)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:467)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:443)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:420)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
```

**Comment by etanshaul** [comment]
fixed with release 20.2.1 on 2/18/20
