### ISSUE TITLE
HttpResponseException: 404 Not Found /userinfo/email has been shut down

### ISSUE THREAD

**Issue by fsladkey** [GoogleCloudPlatform/cloud-code-intellij#2710]
```
com.google.api.client.http.HttpResponseException: 404 Not Found
/userinfo/email has been shut down. Please use the most modern version of this endpoint, https://openidconnect.googleapis.com/v1/userinfo, which accepts the same credentials.
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1061)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.queryEmail(GoogleLoginState.java:507)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.updateUserCredentials(GoogleLoginState.java:419)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.logInWithLocalServer(GoogleLoginState.java:359)
	at com.google.cloud.tools.intellij.login.IntegratedIntellijGoogleLoginService$1.run(IntegratedIntellijGoogleLoginService.java:219)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fsladkey** [comment]
Actually, this report is new but from an old version of the plugin. The issue has already been resolved in newer versions.

**Comment by fsladkey** [comment]
Fixed in this PR https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/981
