### ISSUE TITLE
Managed k8s dependencies throw exception in unssuported operating system

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2725]
Investigation need to determine course of action. E.g. enable support for this OS. 

From exception report:
```
java.lang.RuntimeException at ManagedDependencyFileManager.getPlatformSpecificDepsDir : Unsupported operating system -- cannot use managed dependencies
Stack trace:
java.lang.RuntimeException: Unsupported operating system -- cannot use managed dependencies
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDependencyFileManager.getPlatformSpecificDepsDir(ManagedDependencyFileManager.kt:173)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDependencyFileManager.<init>(ManagedDependencyFileManager.kt:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:580)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.doGetService(PlatformComponentManagerImpl.kt:356)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:343)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDependencyFileManager$Companion.getInstance(ManagedDependencyFileManager.kt:43)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.getManagedKubectlVersion(KubectlExecutorService.kt:180)
	at com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsConfigurable$setMangedDependancyVersions$1$kubectlVersion$1.invokeSuspend(KubernetesSettingsConfigurable.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
```

On FreeBSD

**Comment by etanshaul** [comment]
I did not even know intellij worked in freebsd tbh.

**Comment by ivanporty** [comment]
I still remember this discussion how can we ever encounter unsupported platforms with managed dependencies - and here we go! Good we have this diagnostic message and know we cannot really proceed with most of the functionality. 

What is the question here - show a notification as well so users know?

**Comment by etanshaul** [comment]
I left it vague intentionally as to how we approach this - tbd. I think it is correct that we raised an IDE exception here, otherwise we wouldn't have been notified.

**Comment by peterlin741** [comment]
Made an issue to track:
https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1522

Let's move discussions there?

**Comment by jmah-cc** [comment]
Closing as these Operating Systems are not supported by JetBrains IDEs, nothing we can do on our side.
