### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.notification.NotificationGroup.createNotification

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2741]
```
Stack trace:
java.lang.NoSuchMethodError: com.intellij.notification.NotificationGroup.createNotification$default(Lcom/intellij/notification/NotificationGroup;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/intellij/notification/NotificationType;Lcom/intellij/notification/NotificationListener;ILjava/lang/Object;)Lcom/intellij/notification/Notification;
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDepsInstallerTask.onSuccess(ManagedDepsInstallerTask.kt:68)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerTask.onSuccess(InstallerTask.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$1(CoreProgressManager.java:420)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

app.name.version
PyCharm
app.version.major
2019
app.version.minor
3.4
java.version
1.8.0_232
java.vm.vendor
AdoptOpenJDK
os.name
Mac OS X
plugin.version
20.4.2-SNAPSHOT

**Comment by etanshaul** [comment]
@ivanporty you didn't trigger this by any chance did you? I see the `2.4.2-SNAPSHOT` plugin version here.

**Comment by ivanporty** [comment]
Nope, I didn't

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1803)

**Comment by etanshaul** [comment]
fixed, and merged. Will be out in the next release.

**Comment by ivanporty** [comment]
This should not be an issue with lowest supported version builds.
