### ISSUE TITLE
java.lang.IllegalArgumentException at CredentialedUserRoster.$$$reportNull$$$0 - CredentialedUserRoster.setActiveUser must not be null

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2745]
Cloud Code for IntelliJ version: 19.5.3
IntelliJ version: 2018.3.6
OS: Linux

Related to : https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/623 and https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/601

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'userEmail' of com/google/cloud/tools/intellij/login/CredentialedUserRoster.setActiveUser must not be null
	at com.google.cloud.tools.intellij.login.CredentialedUserRoster.$$$reportNull$$$0(CredentialedUserRoster.java)
	at com.google.cloud.tools.intellij.login.CredentialedUserRoster.setActiveUser(CredentialedUserRoster.java)
	at com.google.cloud.tools.intellij.login.IntegratedIntellijGoogleLoginService.setActiveUser(IntegratedIntellijGoogleLoginService.java:312)
	at com.google.cloud.tools.intellij.login.ui.GoogleLoginUsersPanel.valueChanged(GoogleLoginUsersPanel.java:248)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1796)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1810)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.JList.setValueIsAdjusting(JList.java:2140)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseReleased(BasicListUI.java:2796)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by etanshaul** [comment]
is this in an old plugin version? I suspect its due to the deprecated login endpoint.

**Comment by peterlin741** [comment]
> is this in an old plugin version? I suspect its due to the deprecated login endpoint.

Checking, it is indeed an old version

Cloud Code for IntelliJ version: 19.5.3
