### ISSUE TITLE
AlreadyDisposedException: Cannot create Project

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2746]
- Webstorm 2020.1
- Cloud Code for IntelliJ version: 20.4.2
- OS: Mac OS X

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create Project (name=publisher-backend, containerState=DISPOSE_COMPLETED, componentStore={DIRECTORY_NAME})  because container is already disposed (container=Project (name=publisher-backend, containerState=DISPOSE_COMPLETED, componentStore={DIRECTORY_NAME}) )
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatNotDisposedCompletely(ComponentManagerImpl.kt:424)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:400)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:379)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:24)
	at com.google.cloud.tools.intellij.languageclient.ClientStateHolder$Companion.instance(ClientStateHolder.kt:41)
	at com.google.cloud.tools.intellij.languageclient.SettingsListenerProjectComponent$projectOpened$1.enabled(SettingsListenerProjectComponent.kt:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:549)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
	at com.sun.proxy.$Proxy197.enabled(Unknown Source)
	at com.google.cloud.tools.intellij.kubernetes.settings.KubernetesSettingsService.setKubernetesEditingFeaturesEnabled(KubernetesSettingsService.kt:132)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invokeSuspend(LanguageServerProjectComponent.kt:72)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$setupServer$2.invoke(LanguageServerProjectComponent.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent.setupServer(LanguageServerProjectComponent.kt:61)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectComponent$projectOpened$1.invokeSuspend(LanguageServerProjectComponent.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by peterlin741** [comment]
Fixed
