### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException at StringLatin1.charAt : String index out of range: 92

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2750]
- Cloud Code for IntelliJ version: 20.4.2
- IntelliJ: 2019.3.4
- OS: Windows 10

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 93
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.intellij.execution.process.AnsiStreamingLexer.advance(AnsiStreamingLexer.java:75)
	at com.intellij.execution.process.AnsiEscapeDecoder.escapeText(AnsiEscapeDecoder.java:69)
	at com.intellij.remoteServer.impl.runtime.log.LoggingHandlerImpl$Colored.print(LoggingHandlerImpl.java:94)
	at com.google.cloud.tools.intellij.appengine.java.cloud.standard.AppEngineStandardStage.lambda$stage$0(AppEngineStandardStage.java:60)
	at com.google.cloud.tools.appengine.operations.cloudsdk.process.LegacyProcessHandler$1.run(LegacyProcessHandler.java:100)
```

**Comment by etanshaul** [comment]
closing due to no instances of this error in over 6 months

**Comment by etanshaul** [comment]
new report with this error

**Comment by HolimaX** [comment]
Same on Android Studio 4.2.2

**Comment by etanshaul** [comment]
looking into this still. I have a possible fix.
