### ISSUE TITLE
java.lang.ClassNotFoundException at PluginClassLoader.loadClass : kotlin.jvm.functions.Function4 

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2752]
- Cloud Code for IntelliJ version: 20.4.2
- OS: Mac OS X
- Pycharm 2019.3.4

`java.lang.ClassNotFoundException at PluginClassLoader.loadClass : kotlin.jvm.functions.Function4 PluginClassLoader[com.google.gct.core, 20.4.2] com.intellij.ide.plugins.cl.PluginClassLoader@5e65068b`

```
java.lang.NoClassDefFoundError: kotlin/jvm/functions/Function4
	at kotlin.reflect.jvm.internal.structure.ReflectClassUtilKt.<clinit>(reflectClassUtil.kt:45)
	at kotlin.reflect.jvm.internal.RuntimeTypeMapper.mapJvmClassToKotlinClassId(RuntimeTypeMapper.kt:273)
	at kotlin.reflect.jvm.internal.KClassImpl.getClassId(KClassImpl.kt:183)
	at kotlin.reflect.jvm.internal.KClassImpl.access$getClassId$p(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$simpleName$2.invoke(KClassImpl.kt:61)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$simpleName$2.invoke(KClassImpl.kt:44)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getSimpleName(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getSimpleName(KClassImpl.kt:231)
	at com.google.cloud.tools.intellij.kubernetes.explorer.tree.ClusterGroupNode$refreshNode$1$1.invokeSuspend(ClusterNode.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.functions.Function4 PluginClassLoader[com.google.gct.core, 20.4.2] com.intellij.ide.plugins.cl.PluginClassLoader@5e65068b
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 16 more
```

**Comment by peterlin741** [comment]
Closing since not reproducible, Can reopen if we see this again
