### ISSUE TITLE
java.lang.AssertionError: rootDir must be verified to be directory beforehand.

### ISSUE THREAD

**Issue by fsladkey** [GoogleCloudPlatform/cloud-code-intellij#2753]
- Cloud Code for IntelliJ version: 20.4.2
- OS: Windows 10
- IntelliJ IDEA 2020.1

`java.lang.AssertionError: rootDir must be verified to be directory beforehand.`

```
java.lang.AssertionError: rootDir must be verified to be directory beforehand.
	at kotlin.io.FileTreeWalk$DirectoryState.<init>(FileTreeWalk.kt:62)
	at kotlin.io.FileTreeWalk$FileTreeWalkIterator$BottomUpDirectoryState.<init>(FileTreeWalk.kt:117)
	at kotlin.io.FileTreeWalk$FileTreeWalkIterator.directoryState(FileTreeWalk.kt:91)
	at kotlin.io.FileTreeWalk$FileTreeWalkIterator.gotoNext(FileTreeWalk.kt:110)
	at kotlin.io.FileTreeWalk$FileTreeWalkIterator.computeNext(FileTreeWalk.kt:80)
	at kotlin.collections.AbstractIterator.tryToComputeNext(AbstractIterator.kt:42)
	at kotlin.collections.AbstractIterator.hasNext(AbstractIterator.kt:29)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.JibInitSecurityService.hasGradleBuildFiles(JibInitSecurityService.kt:86)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.JibInitSecurityService.isJibInitAllowed(JibInitSecurityService.kt:57)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.executeSkaffold(SkaffoldExecutorService.kt:127)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.executeSkaffold$default(SkaffoldExecutorService.kt:119)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.getSkaffoldOutputBlocking(SkaffoldExecutorService.kt:402)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService.canGenerateConfiguration(SkaffoldInitService.kt:97)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService$notifyUserIfGenerationPossible$1$canGenerateConfiguration$1.invokeSuspend(SkaffoldInitService.kt:201)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment]
we just got another repot. I think it is only the second one, but adding to the record.

**Comment by fsladkey** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2918)

**Comment by fsladkey** [comment]
Downgrading to p3 as we haven't seen this in a while. We may just be able to close it if it doesn't show up again.

**Comment by etanshaul** [comment]
closing as stale
