### ISSUE TITLE
java.util.ConcurrentModificationException at ArrayList$Itr.checkForComodification : __NONE___

### ISSUE THREAD

**Issue by kkrithika** [GoogleCloudPlatform/cloud-code-intellij#2759]
- Cloud Code for IntelliJ version: 2019.3.4
- OS: Windows 10
- App Name: IntelliJ IDEA

Stack Trace
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
	at com.google.cloud.tools.intellij.cloudrun.CloudRunProcessHandler$destroyProcess$1$1.invokeSuspend(CloudRunProcessHandler.kt:231)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment]
closing is stale. will reopen if new reports come in.
