### ISSUE TITLE
Cloud Source Repos: java.lang.Throwable: GitRepository is null for root file://**/**

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2765]
Pycharm 2020.1
Plugin 20.4.1

```
java.lang.Throwable: GitRepository is null for root file://**/**
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction$1.run(SetupCloudRepositoryAction.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
```

**Comment by ivanporty** [comment]
This looks similar:
```
Stack trace:
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'root' of com/google/cloud/tools/intellij/csr/SetupCloudRepositoryAction.createEmptyGitRepository must not be null
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.$$$reportNull$$$0(SetupCloudRepositoryAction.java)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.createEmptyGitRepository(SetupCloudRepositoryAction.java)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction.access$100(SetupCloudRepositoryAction.java:90)
	at com.google.cloud.tools.intellij.csr.SetupCloudRepositoryAction$1.run(SetupCloudRepositoryAction.java:184)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```


app.name.version
PyCharm
app.version.major
2020
app.version.minor
1.2
java.version
11.0.7
java.vm.vendor
JetBrains s.r.o.
os.name
Windows 10
plugin.version
20.6.1

**Comment by peterlin741** [comment]
Closing, since we haven't seen this issue in a while. Feel free to reopen if this issue is seen again.
