### ISSUE TITLE
Builder detection error running in dev mode

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2776]
Feel free to close this if this is being worked on. But I wanted to make sure to track everything I see:

Simply running in dev mode on `master` and opening a Run Config.

```
2020-06-04 10:01:01,467 [  51683]   WARN - fold.run.ui.SkaffoldBuildPanel - Failed to read artifacts from skaffold yaml file 
expected '<document start>', but found Scalar
 in 'reader', line 1, column 21:
    apiVersion: skaffold/v2beta4
                        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:224)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:66)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldBuildPanel$updateArtifactSettings$1$skaffoldYamlConfig$1.invokeSuspend(SkaffoldBuildPanel.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment]
Kamino closed and cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/1957)

**Comment by etanshaul** [comment]
wrong repo. closing
