### ISSUE TITLE
NPE from Skaffold Run Config in SkaffoldRunConfigurationSettingsEditor.resetEditorFrom

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2800]
```
java.lang.NullPointerException
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverImmediately(MessageBusConnectionImpl.java:60)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.dispatchPendingEvents(FileManagerImpl.java:307)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:374)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:139)
	at com.intellij.psi.impl.PsiDocumentManagerBase.getCachedPsiFile(PsiDocumentManagerBase.java:121)
	at com.intellij.refactoring.suggested.SuggestedRefactoringChangeListener$MyDocumentListener.beforeDocumentChange(SuggestedRefactoringChangeListener.kt:194)
	at jdk.internal.reflect.GeneratedMethodAccessor277.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy114.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.beforeChangedUpdate(DocumentImpl.java:853)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:791)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:657)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:590)
	at com.intellij.ui.EditorTextField.lambda$setText$1(EditorTextField.java:282)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:980)
	at com.intellij.ui.EditorTextField.lambda$setText$2(EditorTextField.java:276)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.ui.EditorTextField.setText(EditorTextField.java:275)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.resetEditorFrom(SkaffoldRunConfigurationSettingsEditor.kt:428)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.resetEditorFrom(SkaffoldRunConfigurationSettingsEditor.kt:79)
```

https://listnrcrash.corp.google.com/product/717949/report/1000000802288792030
Idea 2020.2
CC 20.6.1-202

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2249)

**Comment by etanshaul** [comment]
closing as stale

**Comment by etanshaul** [comment]
re-opening to confirm in 2020.3 / EAP
