### ISSUE TITLE
UnsatisfiedLinkError: Unable to load library 'CoreFoundation'

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2816]
```
java.lang.UnsatisfiedLinkError: Unable to load library 'CoreFoundation':
dlopen(libCoreFoundation.dylib, 9): image not found
dlopen(libCoreFoundation.dylib, 9): image not found
Native library (darwin/libCoreFoundation.dylib) not found in resource path (/Applications/PhpStorm.app/Contents/lib/bootstrap.jar:/Applications/PhpStorm.app/Contents/lib/extensions.jar:/Applications/PhpStorm.app/Contents/lib/util.jar:/Applications/PhpStorm.app/Contents/lib/jdom.jar:/Applications/PhpStorm.app/Contents/lib/log4j.jar:/Applications/PhpStorm.app/Contents/lib/trove4j.jar:/Applications/PhpStorm.app/Contents/lib/jna.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.intellij.util.text.DateFormatUtil.getMacFormats(DateFormatUtil.java:363)
	at com.intellij.util.text.DateFormatUtil.getDateTimeFormats(DateFormatUtil.java:303)
	at com.intellij.util.text.DateFormatUtil.<clinit>(DateFormatUtil.java:46)
	at com.intellij.openapi.wm.impl.status.StatusPanel$5.run(StatusPanel.java:197)
	at com.intellij.openapi.wm.impl.status.StatusPanel.updateText(StatusPanel.java:206)
	at com.intellij.openapi.wm.impl.status.InfoAndProgressPanel.setText(InfoAndProgressPanel.java:348)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.lambda$setInfo$5(IdeStatusBarImpl.java:398)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2254)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.setInfo(IdeStatusBarImpl.java:396)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:632)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:384)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:187)
	at com.sun.proxy.$Proxy123.setInfo(Unknown Source)
	at com.intellij.openapi.wm.StatusBar$Info.set(StatusBar.java:52)
	at com.intellij.notification.LogModel.setStatusMessage(LogModel.java:71)
	at com.intellij.notification.LogModel.addNotification(LogModel.java:43)
	at com.intellij.notification.EventLog$ProjectTracker.printNotification(EventLog.java:505)
	at com.intellij.notification.EventLog$ProjectTracker.access$400(EventLog.java:445)
	at com.intellij.notification.EventLog$ProjectTracker$1.notify(EventLog.java:465)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:632)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:384)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:187)
	at com.sun.proxy.$Proxy71.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:83)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:77)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2254)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:77)
	at com.intellij.notification.Notification.notify(Notification.java:365)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDepsInstallerTask.onSuccess(ManagedDepsInstallerTask.kt:73)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.InstallerTask.onSuccess(InstallerTask.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager.finishTask(CoreProgressManager.java:549)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$6(CoreProgressManager.java:470)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 77 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 77 more
	Suppressed: java.io.IOException: Native library (darwin/libCoreFoundation.dylib) not found in resource path (/Applications/PhpStorm.app/Contents/lib/bootstrap.jar:/Applications/PhpStorm.app/Contents/lib/extensions.jar:/Applications/PhpStorm.app/Contents/lib/util.jar:/Applications/PhpStorm.app/Contents/lib/jdom.jar:/Applications/PhpStorm.app/Contents/lib/log4j.jar:/Applications/PhpStorm.app/Contents/lib/trove4j.jar:/Applications/PhpStorm.app/Contents/lib/jna.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 77 more
```

### Aditional Information

- IDE type (e.g. IntelliJ, Pycharm): PhpStorm
- IDE version: 2020.2
- Cloud Code version (Settings > Plugins > Cloud Code): 20.6.1-202
- Operating System: Mac OS X

**Comment by matthewmichihara** [comment]
This looks like a duplicate of https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2808

**Comment by peterlin741** [comment]
> This looks like a duplicate of #2808

closing
