### ISSUE TITLE
java.nio.file.NoSuchFileException: <...>/JetBrains/IdeaIC2020.2/google-cloud-code/lib/core-20.8.2-202.jar

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2825]
```
java.nio.file.NoSuchFileException: <...>/JetBrains/IdeaIC2020.2/google-cloud-code/lib/core-20.8.2-202.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at com.intellij.util.lang.JarLoader.createZipFile(JarLoader.java:318)
	at com.intellij.util.lang.JarLoader.getZipFile(JarLoader.java:308)
	at com.intellij.util.lang.JarLoader.getResource(JarLoader.java:218)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.findInLoader(ClassPath.java:373)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:368)
	at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:365)
	at com.intellij.util.lang.ClasspathCache.iterateLoaders(ClasspathCache.java:157)
	at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:101)
	at com.intellij.util.lang.UrlClassLoader.findResourceImpl(UrlClassLoader.java:438)
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:431)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findOwnResource(PluginClassLoader.java:293)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:287)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3218)
	at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
	at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
	at com.google.cloud.tools.intellij.kubernetes.util.KubernetesCoreBundle.message(KubernetesCoreBundle.kt:37)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDepsInstallerTask.<init>(ManagedDepsInstallerTask.kt:47)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.ManagedDepsInstallerTask.<init>(ManagedDepsInstallerTask.kt:39)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.DependencyInstaller.getInstallerTasks(DependencyInstaller.kt:139)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.DependencyInstaller.access$getInstallerTasks(DependencyInstaller.kt:48)
	at com.google.cloud.tools.intellij.kubernetes.dependencies.DependencyInstaller$installDependencies$1.invokeSuspend(DependencyInstaller.kt:108)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

```

app.name.version
IntelliJ IDEA
app.version.major
2020
app.version.minor
2.2
java.version
11.0.8
java.vm.vendor
JetBrains s.r.o.
os.name
Linux
plugin.version
20.8.2-202
```

**Comment by matthewmichihara** [comment]
I've seen a few reports of this but haven't been able to reproduce. I see related looking issues in the jetbrains issue tracker but no further insights/solutions
- https://youtrack.jetbrains.com/issue/DEXP-556661

**Comment by matthewmichihara** [comment]
Another youtrack report that looks very similar to this one: https://youtrack.jetbrains.com/issue/SCL-17766

**Comment by matthewmichihara** [comment]
I haven't seen instances of this since December, closing.
