### ISSUE TITLE
CloudRunDevelopProcessHandler - DevelopProcessHandlerException: There was an error pausing Minikube

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2830]
- Cloud Code for IntelliJ version: Php Storm 2020.2.2
- Plugin: 20.9.1-202
- OS: Mac OS X

```
com.google.cloud.tools.intellij.cloudrun.develop.CloudRunDevelopProcessHandler$DevelopProcessHandlerException: There was an error pausing Minikube. Please try again or check Minikube status in Settings > Cloud Code > Cloud SDK.

	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver.executeMinikube(CloudRunMinikubeDriver.kt:257)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver.cleanupMinikube(CloudRunMinikubeDriver.kt:139)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver$initialize$1.run(CloudRunMinikubeDriver.kt:124)
	at com.google.cloud.tools.intellij.process.MultipleProcessHandler$destroyProcess$1$1.invokeSuspend(MultipleProcessHandler.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment]
@matthewmichihara if you have some bandwidth, wanna take a look at this? I briefly investigated before last release and wasn't able to easily repro - though @fsladkey found a contrived way involving breaking the dependencies mid-run (which I doubt is what triggered this report.

**Comment by matthewmichihara** [comment]
Fixed by https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2844
