### ISSUE TITLE
java.lang.AssertionError: Unexpected content storage modification

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2831]
- Cloud Code for IntelliJ version: 20.9.1-202
- OS: Windows 10
- Plugin: Webstorm 2020.2.3

```
java.lang.AssertionError: Unexpected content storage modification: page=25; newRecord=44027
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findOrCreateContentRecord(FSRecords.java:1797)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$3600(FSRecords.java:55)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.lambda$writeBytes$0(FSRecords.java:1708)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeAndHandleErrors(FSRecords.java:990)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.access$300(FSRecords.java:55)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.writeBytes(FSRecords.java:1701)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$ContentOutputStream.access$3200(FSRecords.java:1682)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.writeContent(FSRecords.java:1647)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.writeContent(PersistentFSImpl.java:254)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.storeContentToStorage(PersistentFSImpl.java:652)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.access$100(PersistentFSImpl.java:56)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$2.close(PersistentFSImpl.java:642)
	at java.base/sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
	at java.base/sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
	at java.base/java.io.InputStreamReader.close(InputStreamReader.java:200)
	at java.base/java.io.BufferedReader.close(BufferedReader.java:528)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:53)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.isSkaffoldFile(SkaffoldFileService.kt:57)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector$projectOpened$1$1$checkForSkaffoldFile$1.run(SkaffoldConfigurationDetector.kt:99)
	at com.intellij.util.ui.update.Update$1.run(Update.java:108)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:64)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2274)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by etanshaul** [comment]
closing as this is relatively old; also seems like an edge case. we'll reopen if it happens again.
