### ISSUE TITLE
The Google Cloud SDK could not be found in the customary locations and no path was provided.

### ISSUE THREAD

**Issue by grmoon** [GoogleCloudPlatform/cloud-code-intellij#2839]
*Platform:* IntelliJ IDEA
*Plugin Verstion:* 2020.2.3
*OS:* Windows 10

```
com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkNotFoundException: The Google Cloud SDK could not be found in the customary locations and no path was provided.
	at com.google.cloud.tools.appengine.operations.CloudSdk$Builder.discoverSdkPath(CloudSdk.java:329)
	at com.google.cloud.tools.appengine.operations.CloudSdk$Builder.build(CloudSdk.java:300)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud(CloudSdkAuthWrapper.kt:204)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud$default(CloudSdkAuthWrapper.kt:199)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.getConfigHelper(CloudSdkAuthWrapper.kt:170)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkTokenExpiryScheduler.scheduleTokenExpiryUpdate(CloudSdkTokenExpiryScheduler.kt:47)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService$loadPersistedCredentials$1.invokeSuspend(CloudSdkLoginService.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by grmoon** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2959)
