### ISSUE TITLE
kotlinx.coroutines.CompletionHandlerException

### ISSUE THREAD

**Issue by grmoon** [GoogleCloudPlatform/cloud-code-intellij#2842]
**Platform**: IntelliJ IDEA
**Plugin Version**: 2020.2.3
**OS**: Windows 10

```
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler ChildCompletion[ChildHandle["coroutine#295":DeferredCoroutine{Cancelled}@3fdc1fa7], CompletedExceptionally[java.util.concurrent.TimeoutException: Process timed out.]] for "coroutine#295":DeferredCoroutine{Cancelled}@3fdc1fa7
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1460)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:304)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: java.lang.ExceptionInInitializerError
	at kotlin.ExceptionsKt__ExceptionsKt.addSuppressed(Exceptions.kt:48)
	at kotlinx.coroutines.JobSupport.addSuppressedExceptions(JobSupport.kt:1430)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:212)
	at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:881)
	at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:27)
	at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1091)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1456)
	... 11 more
Caused by: java.lang.ClassCastException: Instance classloader: com.intellij.util.lang.UrlClassLoader@7d907bac, base type classloader: PluginClassLoader[PluginDescriptor(name=Cloud Code, id=com.google.gct.core, path=path\to\google-cloud-code, version=20.10.1-202)] com.intellij.ide.plugins.cl.PluginClassLoader@6c5e5e28
	at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:41)
	... 18 more
Caused by: java.lang.ClassCastException: class kotlin.internal.jdk8.JDK8PlatformImplementations cannot be cast to class kotlin.internal.PlatformImplementations (kotlin.internal.jdk8.JDK8PlatformImplementations is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @7d907bac; kotlin.internal.PlatformImplementations is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6c5e5e28)
	... 19 more
```

**Comment by grmoon** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2977)

**Comment by etanshaul** [comment]
closing as outdated
