### ISSUE TITLE
com.intellij.serialization.SerializationException: Please annotate non-default constructor with PropertyMapping

### ISSUE THREAD

**Issue by pahan35** [GoogleCloudPlatform/cloud-code-intellij#2843]
### Expected Behavior
No exceptions

### Actual Behavior
Exception on startup 
> com.intellij.serialization.SerializationException: Please annotate non-default constructor with PropertyMapping (beanClass=com.google.cloud.tools.intellij.appengine.java.gradle.AppEngineGradleModule)
	at com.intellij.serialization.BeanBinding.createUsingCustomConstructor(BeanBinding.kt:96)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:19)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:253)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:225)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:220)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:94)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:253)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:225)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:220)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:94)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:253)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:225)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:220)
	at com.intellij.serialization.Binding$DefaultImpls.deserialize(Binding.kt:16)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:20)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:253)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:225)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:220)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:30)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:21)
	at com.intellij.serialization.IonObjectSerializer.doRead(IonObjectSerializer.kt:147)
	at com.intellij.serialization.IonObjectSerializer.readVersioned(IonObjectSerializer.kt:95)
	at com.intellij.serialization.VersionedFile.readAndHandleErrors(VersionedFile.kt:55)
	at com.intellij.serialization.VersionedFile.readList(VersionedFile.kt:42)
	at com.intellij.serialization.VersionedFile.readList$default(VersionedFile.kt:41)
	at com.intellij.serialization.VersionedFile.readList(VersionedFile.kt)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.load(ExternalProjectsDataStorage.java:406)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.load(ExternalProjectsDataStorage.java:113)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsManagerImpl.init(ExternalProjectsManagerImpl.java:183)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity.runActivity(ExternalSystemStartupActivity.java:21)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:301)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivities$4(StartupManagerImpl.java:227)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:295)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:155)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA EAP
- IDE version: Build #IU-203.5419.21, built on October 28, 2020
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Y
  - Version of the Cloud SDK: 316.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): N
- Operating System: macOS 10.15.7

**Comment by fsladkey** [comment]
Hey there @pahan35, thanks for the report! We'll take a look and follow up here.

**Comment by fsladkey** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/2979)

**Comment by fsladkey** [comment]
This is fixed in the next release. Thanks again for the report!
