### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal base64 character in Base64$Decoder.decode

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2846]
PhpStorm 2020.2.3
Cloud Code 20.10.1-202
macOS

```
java.lang.IllegalArgumentException: Illegal base64 character <...>
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:743)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:535)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:558)
	at com.google.cloud.tools.intellij.secretmanager.SecretManagerExecutorService.decodeSecretVersionValue(SecretManagerExecutorService.kt:201)
	at com.google.cloud.tools.intellij.secretmanager.SecretManagerExecutorService.accessSecretVersion(SecretManagerExecutorService.kt:193)
	at com.google.cloud.tools.intellij.secretmanager.AccessSecretValueDialogWrapper$setupRootPanel$1$secretValue$1.invokeSuspend(AccessSecretValueDialogWrapper.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by etanshaul** [comment]
@peterlin741 once the next release is behind us, wanna see if you can find something? (assigning to you tentatively but reassign back to me if not)

**Comment by matthewmichihara** [comment]
Fixed in the next release.
