### ISSUE TITLE
javax.imageio.IIOException: Can't get input stream from URL!

### ISSUE THREAD

**Issue by nicolasduminil** [GoogleCloudPlatform/cloud-code-intellij#2848]
### Expected Behavior
Starting Intellij IDEA 2020.2 without exceptions in the log file
### Actual Behavior
Using the last release of the GCP plugin, the following exception is raised when the IDE starts:

### Additional Information
javax.imageio.IIOException: Can't get input stream from URL!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
        at com.google.cloud.tools.intellij.login.GoogleLoginUtils.lambda$provideUserPicture$0(GoogleLoginUtils.java:68)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://lh3.googleusercontent.com/a-/AOh14GjIafDMpgv4rNe58WYXd4UxLPQsHHsJhNPx4Uu0=s96-c=s96-c

- IDE type: IntelliJ IDEA
- IDE version: 2020.2
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK): 317.0.0
  - Are you allowing the plugin to manage the Cloud SDK: 
  - Version of the Cloud SDK: 317.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.15.0
- Operating System: Ubuntu 20.04 LTS

**Comment by matthewmichihara** [comment]
Thanks for the report, we've been able to reproduce.

**Comment by matthewmichihara** [comment]
This is fixed in the next release.
