### ISSUE TITLE
Cloud code fails to install google managed sdk

### ISSUE THREAD

**Issue by jeyase** [GoogleCloudPlatform/cloud-code-intellij#2849]
I am using intellij IDEA community 2020.2.3 Community version . After installing Cloud Code plugin. it is failing to install managed google cloud SDK , it is failing with the below errorManaged google cloud SDK : Managed google cloud sdk installation failed : com.google.cloud.tools.maangedgooglesdkinstallation.command.commandexitexception:process failed with exit code 1

lease see the snippet rom idea.log

2020-11-09 06:01:44,981 [ 289918] INFO - .login.sdk.CloudSdkAuthWrapper - Login service waiting for Cloud SDK: Preparing Google Cloud SDK (this may take several minutes for first time setup)...

2020-11-09 06:01:44,989 [ 289926] INFO - STDERR - Nov 09, 2020 6:01:44 AM com.google.cloud.tools.managedcloudsdk.install.SdkInstaller install
2020-11-09 06:01:44,989 [ 289926] INFO - STDERR - INFO: Removing stale archive: C:\Users\mjeyase\AppData\Local\google\ct4j-cloud-sdk\downloads\google-cloud-sdk-windows-x86_64-bundled-python.zip
2020-11-09 06:01:44,992 [ 289929] INFO - STDERR - Nov 09, 2020 6:01:44 AM com.google.cloud.tools.managedcloudsdk.install.SdkInstaller install
2020-11-09 06:01:44,992 [ 289929] INFO - STDERR - INFO: Removing stale install: C:\Users\mjeyase\AppData\Local\google\ct4j-cloud-sdk\LATEST
2020-11-09 06:02:02,198 [ 307135] INFO - STDERR - Nov 09, 2020 6:02:02 AM com.google.cloud.tools.managedcloudsdk.install.Downloader download
2020-11-09 06:02:02,198 [ 307135] INFO - STDERR - INFO: Downloading https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk-windows-x86_64-bundled-python.zip to C:\Users\mjeyase\AppData\Local\google\ct4j-cloud-sdk\downloads\google-cloud-sdk-windows-x86_64-bundled-python.zip
2020-11-09 06:02:12,129 [ 317066] INFO - j.ide.actions.RevealFileAction - Exit code 1
2020-11-09 06:02:25,951 [ 330888] INFO - .clearcut.ClearcutLogScheduler - Flushing logs.
2020-11-09 06:02:35,954 [ 340891] WARN - .clearcut.ClearcutLogScheduler - Error getting nextSendWaitMillis. Using default value: 60000 ms.
2020-11-09 06:02:35,954 [ 340891] INFO - .clearcut.ClearcutLogScheduler - Scheduling next log flush in 60000 ms.
2020-11-09 06:03:35,956 [ 400893] INFO - .clearcut.ClearcutLogScheduler - Flushing logs.
2020-11-09 06:03:35,956 [ 400893] INFO - .clearcut.ClearcutLogScheduler - Scheduling next log flush in 60000 ms.
2020-11-09 06:03:48,782 [ 413719] WARN - oud.sdk.ManagedCloudSdkService - Error while installing/updating managed Cloud SDK
com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
at com.google.cloud.tools.managedcloudsdk.command.CommandRunner.run(CommandRunner.java:59)
at com.google.cloud.tools.managedcloudsdk.install.Installer.install(Installer.java:70)
at com.google.cloud.tools.managedcloudsdk.install.SdkInstaller.install(SdkInstaller.java:121)
at com.google.cloud.tools.intellij.cloud.sdk.ManagedCloudSdkService.lambda$installSdk$1(ManagedCloudSdkService.java:323)
at com.google.cloud.tools.intellij.cloud.sdk.ManagedCloudSdkService.executeWithSdkWriteLock(ManagedCloudSdkService.java:387)
at com.google.cloud.tools.intellij.cloud.sdk.ManagedCloudSdkService.installSdk(ManagedCloudSdkService.java:322)
at com.google.cloud.tools.intellij.cloud.sdk.ManagedCloudSdkService.installManagedSdk(ManagedCloudSdkService.java:245)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-09 06:03:48,823 [ 413760] WARN - .login.sdk.CloudSdkAuthWrapper - Error while waiting for Cloud SDK to be ready: Cloud Code requires Cloud SDK to obtain user credentials for GCP. Please ensure your Cloud SDK settings are correct in Settings > Cloud Code > Cloud SDK and try again.
2020-11-09 06:03:48,919 [ 413856] ERROR - llij.ide.plugins.PluginManager - The Google Cloud SDK could not be found in the customary locations and no path was provided.
com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkNotFoundException: The Google Cloud SDK could not be found in the customary locations and no path was provided.
at com.google.cloud.tools.appengine.operations.CloudSdk$Builder.discoverSdkPath(CloudSdk.java:329)
at com.google.cloud.tools.appengine.operations.CloudSdk$Builder.build(CloudSdk.java:300)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud(CloudSdkAuthWrapper.kt:204)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud$default(CloudSdkAuthWrapper.kt:199)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.getConfigHelper(CloudSdkAuthWrapper.kt:170)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkTokenExpiryScheduler.scheduleTokenExpiryUpdate(CloudSdkTokenExpiryScheduler.kt:47)
at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService$loadPersistedCredentials$1.invokeSuspend(CloudSdkLoginService.kt:131)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
2020-11-09 06:03:48,920 [ 413857] ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1 Build #IC-201.6668.121
2020-11-09 06:03:48,921 [ 413858] ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-11-09 06:03:48,921 [ 413858] ERROR - llij.ide.plugins.PluginManager - OS: Windows 10
2020-11-09 06:03:48,921 [ 413858] ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Cloud Code version: 20.10.1-201
2020-11-09 06:03:48,922 [ 413859] ERROR - llij.ide.plugins.PluginManager - Last Action: TechnicalSupport
2020-11-09 06:04:35,957 [ 460894] INFO - .clearcut.ClearcutLogScheduler - Flushing logs.
2020-11-09 06:04:45,958 [ 470895] WARN - .clearcut.ClearcutLogScheduler - Error getting nextSendWaitMillis. Using default value: 60000 ms.
2020-11-09 06:04:45,959 [ 470896] INFO - .clearcut.ClearcutLogScheduler - Scheduling next log flush in 60000 ms.
2020-11-09 06:05:45,960 [ 530897] INFO - .clearcut.ClearcutLogScheduler - Flushing logs.
2020-11-09 06:05:45,960 [ 530897] INFO - .clearcut.ClearcutLogScheduler - Scheduling next log flush in 60000 ms.
2020-11-09 06:06:35,161 [ 580098] WARN - ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2020-11-09 06:06:35,173 [ 580110] WARN - ConfigurableExtensionPointUtil - use other group instead of unexpected one: google
2020-11-09 06:06:35,376 [ 580313] INFO - ateSettings.impl.UpdateChecker - failed to load plugin descriptions from : Malformed URL:
2020-11-09 06:06:39,398 [ 584335] INFO - gins.PluginManagerConfigurable -
java.net.MalformedURLException: Malformed URL:
at com.intellij.util.Urls.newFromEncoded(Urls.kt:63)
at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:101)
at com.intellij.ide.plugins.RepositoryHelper.loadPlugins(RepositoryHelper.java:86)
at com.intellij.ide.plugins.PluginManagerConfigurable.loadRepositoryPlugins(PluginManagerConfigurable.java:1549)
at com.intellij.ide.plugins.PluginManagerConfigurable.access$2000(PluginManagerConfigurable.java:73)
at com.intellij.ide.plugins.PluginManagerConfigurable$7.lambda$createPluginsPanel$3(PluginManagerConfigurable.java:382)
at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-09 06:06:45,961 [ 590898] INFO - .clearcut.ClearcutLogScheduler - Flushing logs.
2020-11-09 06:06:45,961 [ 590898] INFO - .clearcut.ClearcutLogScheduler - Scheduling next log flush in 6000

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3000)

**Comment by etanshaul** [comment]
Still catching up on this problem, and might be a dup, but issue created:

https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3000

**Comment by ivanporty** [comment]
Thank you for your report @jeyase! We sometimes see this kind of error with Windows and our managed SDK installations, but cannot reproduce it easily and you help would be appreciated. If you download `https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk-windows-x86_64-bundled-python.zip`, unzip the downloaded archive, and run `cmd /c install.bat` yourself - will that work for you or will it result in some sort of an error? If you could try this and tell us more, that would help us diagnose. Thanks again!

**Comment by ivanporty** [comment]
And for your Windows setup - are there any specific restrictions on the system, something that would require elevated permissions to install additional tools or work with files?

**Comment by jeyase** [comment]
Hi Ivan,
Thanks for your replies..we are not behind firewall but i enabled proxy to
download the plugins via intellij

when i run install.bat, getting the below message

ERROR ( cloud.components.update) failed ot fetch listing from servers.
check your network setting and try again
Active Code page :  437

**Comment by ivanporty** [comment]
Oh I see so Cloud SDK is not able to connect to its servers directly. Do you have any proxies configured in your IDE specifically, i.e. in this settings pane?

<img width="704" alt="Screen Shot 2020-11-10 at 11 09 36 AM" src="https://user-images.githubusercontent.com/11686100/98699526-3d1da280-2345-11eb-94d5-66bac7ac85f5.png">

**Comment by jeyase** [comment]
Hi Ivan,

I choose auto-detect setting to get the plugins downloaded

**Comment by ivanporty** [comment]
Thanks @jeyase for your confirmation! We are working on increasing Cloud SDK installation reliability, and will try to improve the way it works with proxies as well. When we have updates on this, we will let you know! I also edited the title of the issue to reflect it has to do with proxies.

**Comment by crflanigan** [comment]
Hello, I have noticed this issue as well.
Currently I'm unable to install the SDK.
I have made a Reddit post about this issue [here](https://www.reddit.com/r/googlecloud/comments/k0aeqq/cant_install_google_cloud_sdk_using_various/).

Hope a work around comes at some point.
Thanks in advance!

**Comment by ivanporty** [comment]
Hi @crflanigan thank you for your report! Could you please share the details of your proxy setup - do you use IntelliJ settings for proxies (see screenshot above https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2849#issuecomment-724802472) or your proxies are automatic? You mentioned VPN as well in your Reddit post - does it mean you have both VPN and proxy?

While we are working on the better solution for this, we could try to understand an underlying issue a bit more. You said
> I then tried installing from the Google Archives but I found that I also ran into another issue:
ERROR: (gcloud.components.list) Failed to fetch component listing from server.

It seems you downloaded an archive but Cloud SDK itself is not able to connect to its servers. Here is an article on configuring proxy access for Cloud SDK:
https://cloud.google.com/sdk/docs/proxy-settings#top_of_page

Could you try specifying settings shown in this article such as `gcloud config set proxy/address` etc. or use equivalent environment variables (i.e. `CLOUDSDK_PROXY_ADDRESS`) and let us know if that helps?

**Comment by etanshaul** [comment]
SDK proxy support will be available in the next Cloud Code release

**Comment by etanshaul** [comment]
@jeyase @crflanigan we released Cloud Code `12.20.2` yesterday which respects proxy configuration for `gcloud`. Going to close this issue, but feel free to follow up with any issues / questions you may have. Thanks.

**Comment by wonsuc** [comment]
```
2021-07-26
오전 11:21	Managed Google Cloud SDK
				New version of Managed Google Cloud SDK is available and about to be updated.
				Skip this update
				Disable automatic updates

오전 11:21	Google Cloud SDK: Waiting for Cloud SDK to become available to read GCP credentials...

오전 11:23	Cloud Code initialization: Cloud Code has finished setting up managed Kubernetes dependencies.

오전 11:26	Managed Google Cloud SDK: Managed Google Cloud SDK installation failed: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1.

오전 11:26	Google Cloud SDK: Cloud Code requires Cloud SDK to obtain user credentials for GCP. Please ensure your Cloud SDK settings are correct in Settings | Tools | Cloud Code | Dependencies and try again.

오전 11:26	Error Reading GCP Credentials
				Cloud Code requires Cloud SDK to obtain user credentials for GCP. Please ensure your Cloud SDK settings are correct in Settings | Tools | Cloud Code | Dependencies and try again.
				Open Settings
```

My environment is proxy behind and I manually added a Certification of `*.google.com` to the `C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2\jbr\lib\security\cacerts` file and it seemed working but some of dependencies have problems to download.  

Can I know which urls are being used for entire dependency downloads?

**Comment by peterlin741** [comment]
@wonsuc, we download the [Cloud SDK](https://cloud.google.com/sdk/docs/install), [kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/), [skaffold](https://skaffold.dev/docs/install/), and [minikube](https://github.com/kubernetes/minikube/releases). You can grab the binaries from the respective websites.

Here are the versions in my environment, if that helps:

![image](https://user-images.githubusercontent.com/58699538/127092488-6b6f7864-c928-4ebd-bcb9-5f6285ae8ea2.png)

**Comment by wonsuc** [comment]
@peterlin741 I checked that preference screen and it seems kubectl client and Skaffold is installed and Cloud SDK, minikube are not installed. They must use a different repository instead of `*.google.com` maybe...?

**Comment by wonsuc** [comment]
@peterlin741 and Thanks for giving me the option.

**Comment by peterlin741** [comment]
@wonsuc, no problem!

And you are correct, internally, our Cloud SDK and minikube installations are powered by a different mechanism, through the [appengine-plugins-core](https://github.com/GoogleCloudPlatform/appengine-plugins-core) plugin. If you want to dig deeper, you can look at the `SdkComponentInstaller` class. But essentially, we're using the CLI commands (e.g. `gcloud components install` for minikube).

I would suggest downloading and pointing to the custom binaries as a quick workaround.

**Comment by wonsuc** [comment]
@peterlin741 Thank you so much

**Comment by wonsuc** [comment]
@peterlin741 OK, one more question. 

https://cloud.google.com/sdk/docs/proxy-settings

Does **Cloud Code** plugin provides same proxy setting (as environments) of IntelliJ to **appengine-plugins-core** plugin?

**Comment by ivanporty** [comment]
@wonsuc we use the same system proxy environment for installing Cloud SDK as in the page you linked. To make sure all tools and commands use the proxy, could you please check your IDE proxy settings (see example here https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2849#issuecomment-724802472) are set and point to a valid proxy? If it's set properly, Cloud Code should be able to use it for its tools and Cloud SDK.
