### ISSUE TITLE
MinikubeUnavailableException in MinikubeExecutorService.executeMinikube() (MinikubeGcpAuthManager)

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2852]
Could not resolve Minikube path. Please check Kubernetes dependencies settings (Settings > Cloud Code > Kubernetes), and ensure that Minikube is installed correctly.
error.stacktrace
```
com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeUnavailableException: Could not resolve Minikube path. Please check Kubernetes dependencies settings (Settings > Cloud Code > Kubernetes), and ensure that Minikube is installed correctly.
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeExecutorService.executeMinikube(MinikubeExecutorService.kt:140)
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeGcpAuthManager.isGcpAuthEnabled(MinikubeGcpAuthManager.kt:125)
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeGcpAuthManager.disableGcpAuthAddon(MinikubeGcpAuthManager.kt:89)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver.cleanupMinikube(CloudRunMinikubeDriver.kt:144)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver$initialize$1.run(CloudRunMinikubeDriver.kt:129)
	at com.google.cloud.tools.intellij.process.MultipleProcessHandler$destroyProcess$1$1.invokeSuspend(MultipleProcessHandler.kt:108)
	at (Coroutine boundary.()
	at com.google.cloud.tools.intellij.process.MultipleProcessHandler$destroyProcess$1.invokeSuspend(MultipleProcessHandler.kt:97)
Caused by: com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeUnavailableException: Could not resolve Minikube path. Please check Kubernetes dependencies settings (Settings > Cloud Code > Kubernetes), and ensure that Minikube is installed correctly.
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeExecutorService.executeMinikube(MinikubeExecutorService.kt:140)
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeGcpAuthManager.isGcpAuthEnabled(MinikubeGcpAuthManager.kt:125)
	at com.google.cloud.tools.intellij.kubernetes.minikube.MinikubeGcpAuthManager.disableGcpAuthAddon(MinikubeGcpAuthManager.kt:89)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver.cleanupMinikube(CloudRunMinikubeDriver.kt:144)
	at com.google.cloud.tools.intellij.cloudrun.develop.minikube.CloudRunMinikubeDriver$initialize$1.run(CloudRunMinikubeDriver.kt:129)
	at com.google.cloud.tools.intellij.process.MultipleProcessHandler$destroyProcess$1$1.invokeSuspend(MultipleProcessHandler.kt:108)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

java.version
11.0.8
java.vm.vendor
JetBrains s.r.o.
last.action
Rerun
os.name
Windows 10
plugin.version
20.10.1-202

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3049)

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3050)

**Comment by peterlin741** [comment]
Another instance: https://listnrcrash.corp.google.com/product/717949/report/1000001007121512887

![image](https://user-images.githubusercontent.com/58699538/108241442-d7963a80-7119-11eb-838a-79990854e0e9.png)

**Comment by matthewmichihara** [comment]
Fixed in next release.

**Comment by grmoon** [comment]
https://primes-crash.corp.google.com/product/717949/report/1000001178769249308

**Comment by grmoon** [comment]
Closing again, the crash report in https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/2852#issuecomment-975642524 occurred in 2019.3.5, a version of the IDE no longer supported by Cloud Code
