### ISSUE TITLE
Fatal exception in coroutines machinery for DispatchedContinuation

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2854]
`class kotlinx.coroutines.CoroutinesInternalError at Dispatched.kt : kotlinx.coroutines.DispatchedTask#handleFatalException$kotlinx_coroutines_core:278`

```
Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@22940183, Continuation at com.google.cloud.tools.intellij.util.ProcessExtensionsKt$waitForProcessOutput$1.invokeSuspend(ProcessExtensions.kt)@65b60dda]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers

kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[BlockingEventLoop@22940183, Continuation at com.google.cloud.tools.intellij.util.ProcessExtensionsKt$waitForProcessOutput$1.invokeSuspend(ProcessExtensions.kt)@65b60dda]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(Dispatched.kt:278)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:249)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.google.cloud.tools.intellij.util.ProcessExtensionsKt.waitForProcessOutput(ProcessExtensions.kt:93)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud(CloudSdkAuthWrapper.kt:211)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.executeGcloud$default(CloudSdkAuthWrapper.kt:199)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkAuthWrapper.getCredentialForUser(CloudSdkAuthWrapper.kt:134)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService.getCredentialedUser(CloudSdkLoginService.kt:170)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService.refreshUserCache(CloudSdkLoginService.kt:160)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService.access$refreshUserCache(CloudSdkLoginService.kt:44)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService$loadPersistedCredentials$1$1.invoke(CloudSdkLoginService.kt:131)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService$loadPersistedCredentials$1$1.invoke(CloudSdkLoginService.kt:44)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkTokenExpiryScheduler$scheduleTokenExpiryUpdate$timerTask$1.run(CloudSdkTokenExpiryScheduler.kt:63)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.ExceptionInInitializerError
	at kotlin.ExceptionsKt__ExceptionsKt.addSuppressed(Exceptions.kt:48)
	at kotlinx.coroutines.JobSupport.addSuppressedExceptions(JobSupport.kt:1430)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:212)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	... 18 more
```

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2020.2.3
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-202
- Operating System: Mac OS X
- Java: 11.0.8

**Comment by matthewmichihara** [comment]
not sure what the root issue is here but our coroutine dependency is getting a bit out of date and we should probably update to pick up new bug fixes.

**Comment by axmerc** [comment]
Closing pending future occurrence
