### ISSUE TITLE
NoClassDefFoundError: Could not initialize class io.grpc.ManagedChannelProvider

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2855]
```
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.ManagedChannelProvider
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:37)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.events.SkaffoldEventHandler.newManagedChannel(SkaffoldEventHandler.kt:319)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.events.SkaffoldEventHandler.listenEvents(SkaffoldEventHandler.kt:75)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldCommandLineState$startProcess$1.invokeSuspend(SkaffoldCommandLineState.kt:189)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Goland
- IDE version: 2020.3
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-202
- Operating System: Mac OS X

**Comment by etanshaul** [comment]
this has been fixed and will be out in the next release version `20.12.1`

**Comment by SwiftyWang** [comment]
@etanshaul @peterlin741 Hi bro, May I know how to fix this issue? I encounter the same problem when IDE upgrade for myself Intellij plugin.
Thanks so much!

**Comment by peterlin741** [comment]
Hi @SwiftyWang,

Could you provide the exact steps that you took, so that we can try to reproduce this issue?

For example, what version of the IDE (IntelliJ/ Pycharm/ etc, and major/minor versions) were you using? Did you use the marketplace to upgrade to the latest plugin version, or did you try to install a custom plugin version using a zip file?

Thanks!

**Comment by SwiftyWang** [comment]
Hi @peterlin741,
Thanks for the reply.
The environment is:
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2.1

And The error is the same when my plugin running:
```
java.lang.NoClassDefFoundError: Could not initialize class io.grpc.ManagedChannelProvider
at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
```
I tried to use the latest GRPC lib version or add GRPC jar directly without maven dependence. Both not working.
I saw this plugin faced this issue months ago and could you help to how to fix it? Many thanks!

**Comment by peterlin741** [comment]
Hi @SwiftyWang, do you mean that you are encountering this issue in a plugin that you are developing? Unrelated to Cloud Code?

Our internal fix was updating our dependencies in our `build.gradle.kts` file. We removed `compile("io.grpc:grpc-okhttp")` and `compile("io.grpc:grpc-netty")`, and instead now use `compile("io.grpc:grpc-netty-shaded")`.

**Comment by SwiftyWang** [comment]
@peterlin741 Thank you so much!
Let me try it.
