### ISSUE TITLE
NullPointerException at CPlatformWindow.java

### ISSUE THREAD

**Issue by peterlin741** [GoogleCloudPlatform/cloud-code-intellij#2856]
```
java.lang.NullPointerException
	at java.desktop/sun.lwawt.macosx.CPlatformWindow.getInitialStyleBits(CPlatformWindow.java:446)
	at java.desktop/sun.lwawt.macosx.CPlatformWindow.initialize(CPlatformWindow.java:316)
	at java.desktop/sun.lwawt.LWWindowPeer.<init>(LWWindowPeer.java:190)
	at java.desktop/sun.lwawt.LWToolkit.createDelegatedPeer(LWToolkit.java:212)
	at java.desktop/sun.lwawt.LWToolkit.createDialog(LWToolkit.java:248)
	at java.desktop/sun.lwawt.macosx.LWCToolkit.createDialog(LWCToolkit.java:303)
	at java.desktop/java.awt.Dialog.addNotify(Dialog.java:750)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.addNotify(DialogWrapperPeerImpl.java:638)
	at java.desktop/java.awt.Window.pack(Window.java:824)
	at com.google.cloud.tools.intellij.kubernetes.explorer.addcluster.AddExistingGkeClusterDialog$hideErrorMessage$1.invokeSuspend(AddExistingGkeClusterDialog.kt:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA
- IDE version: 2019.3.5
- Cloud Code version (Settings > Plugins > Cloud Code): 20.10.1-201
- Operating System: Mac OS X

**Comment by matthewmichihara** [comment]
This is coming from`AddExistingGkeClusterDialog`, where we're calling `window.pack()`. I'm pretty sure we don't need to be calling `pack()`. Similar issues on youtrack have been resolved by removing these kinds of calls: https://youtrack.jetbrains.com/issue/MPS-31537

**Comment by axmerc** [comment]
Issue is stale - closing until next encounter
