### ISSUE TITLE
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider

### ISSUE THREAD

**Issue by BenNeighbour** [GoogleCloudPlatform/cloud-code-intellij#2859]
This has been happening ever since I have updated Intellij (IDEA CE 2020.3) to a newer version (today). I am getting this exception from the plugin when running the ```Develop on Kubernetes``` Run Configuration that I usually use with my local Minikube instance to get all of the services in the cluster up and running, and able to Debug in debug mode.

My local Minikube instance is fine shown by the following:
```
(Dev) $ minikube status

minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

I've tried checking for updates, restarting Intellij, and I am still getting the same thing. It must be something in relation to my Intellij Update but we'll have to see...

The full stack trace is:

```
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.ServiceProviders.load(ServiceProviders.java:42)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:37)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.events.SkaffoldEventHandler.newManagedChannel(SkaffoldEventHandler.kt:319)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.events.SkaffoldEventHandler.listenEvents(SkaffoldEventHandler.kt:75)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldCommandLineState$startProcess$1.invokeSuspend(SkaffoldCommandLineState.kt:189)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

I am getting the same behaviour in both ```DEBUG``` mode and ```RUN``` mode.

### Environment Info

- IDE type: IntelliJ 
- IDE version: Community Edition 2020.3
- Cloud Code version:  20.10.1-202
- Skaffold version: v1.14.0
- Operating System: Windows 10 Pro 64-bit

Any help, suggestions or resolutions would be really appreciated so thank you in advance! Thanks

**Comment by matthewmichihara** [comment]
We're having some dependency issues in 2020.3, we plan on pushing an update in a few hours to fix this.

**Comment by BenNeighbour** [comment]
Okay, thanks!

**Comment by matthewmichihara** [comment]
Hey @BenNeighbour, we just published a new release to fix this issue, `20.12.1-202` (https://plugins.jetbrains.com/plugin/8079-cloud-code/versions/stable/104280). Gonna close this issue but please re-open if you're still seeing this problem.

**Comment by BenNeighbour** [comment]
Okay - will do if I face any - I can just check for plugin updates in intellij and it will come up right? Or do I need to do anything else

**Comment by etanshaul** [comment]
@BenNeighbour yes, you should be able just to visit the plugin page and see the update. 

Sometimes there is a slight delay between publishing and when it actually shows up. If it still hasn't showed up and you want to get it immediately you can download `20.12.1-202` from here (use the `stable` channel), and manually point your IDE to it (in the plugin settings you can browse manually to a plugin zip).

**Comment by BenNeighbour** [comment]
All works now
