### ISSUE TITLE
IOException: User limit of inotify instances reached or too many open files

### ISSUE THREAD

**Issue by grmoon** [GoogleCloudPlatform/cloud-code-intellij#2868]
IDE Type: IntelliJ IDEA
IDE Version: 2020.3
Plugin Version: 20.12.1-202
OS: Linux

```
java.io.IOException: User limit of inotify instances reached or too many open files
	at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
	at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkSentinelWatcher.startWatching(CloudSdkSentinelWatcher.kt:47)
	at com.google.cloud.tools.intellij.login.sdk.CloudSdkLoginService$loadPersistedCredentials$1.invokeSuspend(CloudSdkLoginService.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by grmoon** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3213)

**Comment by ivanporty** [comment]
Area was improved and this issue shouldn't happen anymore starting the next release.
