### ISSUE TITLE
Goland 2021.1 EAP Plugin Initialization Error

### ISSUE THREAD

**Issue by SUSTAPLE117** [GoogleCloudPlatform/cloud-code-intellij#2880]
On Goland EAP startup the IDE crashes and the following stacktrace is shown. This happens everytime I try to open IDE when the Cloud Code plugin is enabled:

`Plugin 'com.google.gct.core' failed to initialize and will be disabled. Please restart GoLand.

java.lang.ExceptionInInitializerError
    at com.google.cloud.tools.intellij.analytics.ClearcutUsageTrackerService.trackEvent(ClearcutUsageTrackerService.java:368)
    at com.google.cloud.tools.intellij.startup.CloudToolsPluginInitializationComponent.initComponent(CloudToolsPluginInitializationComponent.java:76)`
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:44)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:57)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:340)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$5(ApplicationImpl.java:342)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:663)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
    at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:342)
    at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:198)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
    at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:782)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:418)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassCastException: class [B cannot be cast to class java.io.InputStream ([B and java.io.InputStream are in module java.base of loader 'bootstrap')
    at com.google.cloud.tools.intellij.analytics.GctTracking.loadActiveUserActions(GctTracking.java:606)
    at com.google.cloud.tools.intellij.analytics.GctTracking.<clinit>(GctTracking.java:639)
    ... 39 more

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm): Goland
- IDE version: GoLand 2021.1 EAP
Build #GO-211.5538.13, built on February 3, 2021
- Cloud Code version (Settings > Plugins > Cloud Code): 21.2.1-202
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Yes
  - Version of the Cloud SDK: Google Cloud SDK 313.0.1
- Operating System: Windows 10

**Comment by etanshaul** [comment]
thank you for reporting issues in the EAP (EAPs are moving targets, so this is very helpful to us)! In my initial testing:

- Can confirm that I also see this exception in GoLand EAP
- The latest stable version of GoLand (2020.3.2) does _not_ have this issue
- The IntelliJ EAP also does _not_ have this issue

We'll investigate a fix for this.

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3458)

**Comment by peterlin741** [comment]
This has been resolved in the latest patch release `21.2.2-210`, which was released today
