### ISSUE TITLE
Cannot create class com.google.cloud.tools.intellij.project.CurrentGcloudProjectLoaderActivity

### ISSUE THREAD

**Issue by grmoon** [GoogleCloudPlatform/cloud-code-intellij#2896]
**IDE**: IntelliJ IDEA
**IDE Version**: 2020.3.2
**Plugin Version**: 21.2.3-202
**OS**: Windows 10

```
com.intellij.diagnostic.PluginException: Cannot create class com.google.cloud.tools.intellij.project.CurrentGcloudProjectLoaderActivity [Plugin: com.google.gct.core]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:725)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.instantiateClass(ExtensionComponentAdapter.java:51)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:133)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.createInstance(ExtensionComponentAdapter.java:43)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:69)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:472)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:294)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:158)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$projectOpened$1(StartupManagerImpl.java:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:684)
	... 22 more
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at com.google.cloud.tools.intellij.cloud.sdk.GcloudService$client$2$executable$1.<init>(GcloudService.kt)
	at com.google.cloud.tools.intellij.cloud.sdk.GcloudService$client$2.invoke(GcloudService.kt:61)
	at com.google.cloud.tools.intellij.cloud.sdk.GcloudService$client$2.invoke(GcloudService.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.cloud.tools.intellij.cloud.sdk.GcloudService.getClient(GcloudService.kt)
	at com.google.cloud.tools.intellij.project.CurrentGcloudProjectLoaderActivity.<init>(CurrentGcloudProjectLoaderActivity.kt:43)
	... 27 more
```

**Comment by grmoon** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3620)

**Comment by grmoon** [comment]
again https://listnrcrash.corp.google.com/product/717949/report/1000001020364351389

**Comment by grmoon** [comment]
Our error reports indicate that this error is only occurring under very specific circumstances that only affect an extremely small subset of users. If you encounter this error and are able to provide information to help us reproduce it, please leave a comment on this issue with:

* Jetbrains IDE you're using
* the version of the IDE
* the version of the Cloud Code Plugin you're using
* the OS you're using
* steps to reproduce the issue

closing for now
