### ISSUE TITLE
org.yaml.snakeyaml.parser.ParserException in SkaffoldSchemaService.skaffoldSchemaUpgradesAvailable

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2929]
```
while parsing a flow sequence
 in 'reader', line 18, column 22:
            valuesFiles: [../../../deployments/{{ .Env.NA ... 
                         ^
expected ',' or ']', but got {
 in 'reader', line 18, column 44:
     ... uesFiles: [../../../deployments/{{ .Env.NAMESPACE }}/pci/60-serv ... 
                                         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry.produce(ParserImpl.java:637)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:208)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:209)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlConfiguration$Companion.loadFromVirtualFileOrProject(SkaffoldYamlConfiguration.kt:79)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlConfiguration.<init>(SkaffoldYamlConfiguration.kt:92)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlConfiguration.<init>(SkaffoldYamlConfiguration.kt:91)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldSchemaService.skaffoldSchemaUpgradesAvailable(SkaffoldSchemaService.kt:180)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.inspections.SkaffoldSchemaUpgradeInspection$SkaffoldSchemaVisitor.checkIfSkaffoldUpgradeIsPossible(SkaffoldSchemaUpgradeInspection.kt:79)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.inspections.SkaffoldSchemaUpgradeInspection$SkaffoldSchemaVisitor.visitElement(SkaffoldSchemaUpgradeInspection.kt:58)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at org.jetbrains.yaml.psi.impl.YAMLKeyValueImpl.accept(YAMLKeyValueImpl.java:222)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:65)
```

**Comment by ivanporty** [comment]
21.4.1-202

**Comment by ivanporty** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/3915)
