### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.winp.Native 	

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2941]
```

java.lang.NoClassDefFoundError: Could not initialize class org.jvnet.winp.Native
	at org.jvnet.winp.WinProcess.kill(WinProcess.java:79)
	at com.intellij.execution.process.OSProcessUtil.killProcess(OSProcessUtil.java:68)
	at com.intellij.execution.process.OSProcessUtil.killProcess(OSProcessUtil.java:60)
	at com.google.cloud.tools.intellij.util.CommandExecutor$processDestroyer$1.invoke(CommandExecutor.kt:42)
	at com.google.cloud.tools.intellij.util.CommandExecutor$processDestroyer$1.invoke(CommandExecutor.kt:33)
	at com.google.cloud.tools.intellij.util.CommandExecutor.tryDestroyProcess(CommandExecutor.kt:127)
	at com.google.cloud.tools.intellij.util.CommandExecutor.isAvailable(CommandExecutor.kt:59)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.isKubectlAvailable(KubectlExecutorService.kt:94)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.getKubectlExecutablePathOrFail(KubectlExecutorService.kt:246)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.executeKubectlBlocking(KubectlExecutorService.kt:151)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlExecutorService.executeKubectlBlocking$default(KubectlExecutorService.kt:149)
	at com.google.cloud.tools.intellij.kubernetes.kubectl.KubectlApi.config(KubectlApi.kt:111)
	at com.google.cloud.tools.intellij.kubernetes.explorer.tree.ClusterGroupNode$refreshNode$2$1.invokeSuspend(ClusterNode.kt:101)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.version
11.0.11
java.vm.vendor
JetBrains s.r.o.
last.action
__NONE___
os.name
Windows 10
plugin.version
21.5.1
```

**Comment by ivanporty** [comment]
Similar
```
Unable to load winp.x64.dll
error.stacktrace
java.lang.UnsatisfiedLinkError: Unable to load winp.x64.dll
	at org.jvnet.winp.Native.load(Native.java:132)
	at org.jvnet.winp.Native.<clinit>(Native.java:93)
	at org.jvnet.winp.WinProcess.kill(WinProcess.java:79)
	at com.intellij.execution.process.OSProcessUtil.killProcess(OSProcessUtil.java:68)
	at com.intellij.execution.process.OSProcessUtil.killProcess(OSProcessUtil.java:60)
	at com.google.cloud.tools.intellij.util.CommandExecutor$processDestroyer$1.invoke(CommandExecutor.kt:42)
	at com.google.cloud.tools.intellij.util.CommandExecutor$processDestroyer$1.invoke(CommandExecutor.kt:33)
	at com.google.cloud.tools.intellij.util.CommandExecutor.tryDestroyProcess(CommandExecutor.kt:127)
	at com.google.cloud.tools.intellij.util.CommandExecutor.isAvailable(CommandExecutor.kt:59)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.isSkaffoldAvailable(SkaffoldExecutorService.kt:98)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.executeSkaffold(SkaffoldExecutorService.kt:123)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.executeSkaffold$default(SkaffoldExecutorService.kt:120)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldExecutorService.getSkaffoldOutputBlocking(SkaffoldExecutorService.kt:440)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService.runSkaffoldInitAnalyze(SkaffoldInitService.kt:156)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService.runSkaffoldInitAnalyze$default(SkaffoldInitService.kt:139)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.init.SkaffoldInitService$notifyUserIfGenerationPossible$1$1.invokeSuspend(SkaffoldInitService.kt:278)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.UnsatisfiedLinkError: ...\AppData\Local\Temp\winp.x6410917941880033437226.dll: Can't find dependent libraries
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.jvnet.winp.Native.loadDll(Native.java:242)
	at org.jvnet.winp.Native.loadByUrl(Native.java:170)
	at org.jvnet.winp.Native.load(Native.java:124)
	... 21 more
```
