### ISSUE TITLE
Cannot create org.jetbrains.idea.maven.importing.MavenPomPathModuleService because container is already disposed

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2956]
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create org.jetbrains.idea.maven.importing.MavenPomPathModuleService because container is already disposed: Module: 'documentstorage-client' (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:522)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:498)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at org.jetbrains.idea.maven.importing.MavenPomPathModuleService.getInstance(MavenPomPathModuleService.java:15)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.findPomFile(MavenProjectsManager.java:757)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.lambda$findProject$5(MavenProjectsManager.java:720)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:227)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:227)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:228)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:72)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:111)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.findProject(MavenProjectsManager.java:719)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.getModuleDependencies(CloudLibraryMavenProjectState.java:221)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.loadManagedLibraries(CloudLibraryMavenProjectState.java:141)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.syncManagedProjectLibraries(CloudLibraryMavenProjectState.java:118)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState$1.projectsScheduled(CloudLibraryMavenProjectState.java:95)
	at org.jetbrains.idea.maven.project.MavenProjectsManager.fireProjectScheduled(MavenProjectsManager.java:1386)
	at org.jetbrains.idea.maven.project.MavenProjectsManager$5.projectsUpdated(MavenProjectsManager.java:494)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.fireProjectsUpdated(MavenProjectsTree.java:1303)
	at org.jetbrains.idea.maven.project.MavenProjectsTree$UpdateContext.fireUpdatedIfNecessary(MavenProjectsTree.java:1363)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.update(MavenProjectsTree.java:474)
	at org.jetbrains.idea.maven.project.MavenProjectsTree.update(MavenProjectsTree.java:438)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessorReadingTask.perform(MavenProjectsProcessorReadingTask.java:65)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor.doProcessPendingTasks(MavenProjectsProcessor.java:143)
	at org.jetbrains.idea.maven.project.MavenProjectsProcessor$1.run(MavenProjectsProcessor.java:112)
	at org.jetbrains.idea.maven.utils.MavenUtil.lambda$runInBackground$6(MavenUtil.java:536)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by peterlin741** [comment]
Our team is still investigating this
