### ISSUE TITLE
Assertion error in SamplesCloneManager.cloneRepositoryToTempDir

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2977]
Plugin 21.7.1
IDEA 2021.1.2
Windows 10

```
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:218)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:227)
	at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:107)
	at git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:68)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareHttpAuth(GitHandlerAuthenticationManager.java:94)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:61)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1039)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:60)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:161)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:119)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:69)
	at git4idea.commands.GitImpl.clone(GitImpl.java:183)
	at git4idea.checkout.GitCheckoutProvider.doClone(GitCheckoutProvider.java:110)
	at com.google.cloud.tools.intellij.git.GitCheckoutService.clone(GitCheckoutService.kt:44)
	at com.google.cloud.tools.intellij.samples.SamplesCloneManager.cloneRepositoryToTempDir(SamplesCloneManager.kt:176)
	at com.google.cloud.tools.intellij.samples.SamplesCloneManager.clone$lambda-0(SamplesCloneManager.kt:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:275)
	at com.google.cloud.tools.intellij.samples.SamplesCloneManager.clone(SamplesCloneManager.kt:80)
	at com.google.cloud.tools.intellij.samples.SamplesModuleBuilder.createModule$lambda-0(SamplesModuleBuilder.kt:103)
	at com.intellij.openapi.project.DumbServiceImpl.doUnsafeRunWhenSmart(DumbServiceImpl.java:256)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:242)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAfterOpened(StartupManagerImpl.kt:397)
```

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4478)
