### ISSUE TITLE
Assertion error deserializing skaffold dev configuration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2978]
https://primes-crash.corp.google.com/product/717949/report/1000001169974761242
plugin 21.7.1
WebStorm
Linux

```
java.lang.AssertionError
	at com.intellij.util.xmlb.AbstractCollectionBinding.deserializeList(AbstractCollectionBinding.java:160)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:94)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:238)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:192)
	at com.intellij.util.xmlb.XmlSerializer.deserializeInto(XmlSerializer.java:73)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldDevConfiguration.readExternal(SkaffoldRunConfigurations.kt:151)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImplKt.deserializeConfigurationFrom(RunnerAndConfigurationSettingsImpl.kt:603)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:226)
	at com.intellij.execution.impl.RCInArbitraryFileManager.loadChangedRunConfigsFromFile$intellij_platform_execution_impl(RCInArbitraryFileManager.kt:154)
	at com.intellij.execution.impl.RunManagerImpl.updateRunConfigsFromArbitraryFiles$intellij_platform_execution_impl(RunManagerImpl.kt:363)
	at com.intellij.execution.impl.RCInArbitraryFileListener$prepareChange$1.afterVfsChange(RCInArbitraryFileListener.kt:62)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.afterVfsChange(AsyncEventSupport.java:139)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport$1.after(AsyncEventSupport.java:70)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:674)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:649)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:422)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:185)
	at com.sun.proxy.$Proxy130.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.fireAfterEvents(PersistentFSImpl.java:1187)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$3.close(PersistentFSImpl.java:787)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.write(LoadTextUtil.java:445)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocumentInWriteAction$4(FileDocumentManagerImpl.java:414)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:326)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.doSaveDocumentInWriteAction(FileDocumentManagerImpl.java:403)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.lambda$doSaveDocument$2(FileDocumentManagerImpl.java:364)
	at com.intellij.openapi.application.WriteAction.lambda$run$1(WriteAction.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:947)
```

**Comment by etanshaul** [comment]
@grmoon something to do with deserializing the run config - can you take a look to see if there is anything actionable here?

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4479)
