### ISSUE TITLE
NullPointerException JavaeeAppServerConfigurationType#createFactory

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2979]
Plugin 21.7.1
IDEA 2021.2
Linux
https://primes-crash.corp.google.com/product/717949/report/1000001169233466690

```
java.lang.NullPointerException
	at com.intellij.javaee.appServers.run.configuration.JavaeeAppServerConfigurationType.createFactory(JavaeeAppServerConfigurationType.java:73)
	at com.intellij.javaee.appServers.run.configuration.JavaeeAppServerConfigurationType.createLocalFactory(JavaeeAppServerConfigurationType.java:78)
	at com.intellij.javaee.appServers.run.configuration.JavaeeAppServerConfigurationType.computeFactories(JavaeeAppServerConfigurationType.java:66)
	at com.intellij.javaee.appServers.run.configuration.JavaeeAppServerConfigurationType.lambda$new$0(JavaeeAppServerConfigurationType.java:38)
	at com.intellij.openapi.util.NotNullLazyValue$1.compute(NotNullLazyValue.java:56)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:32)
	at com.intellij.javaee.appServers.run.configuration.JavaeeAppServerConfigurationType.getConfigurationFactories(JavaeeAppServerConfigurationType.java:92)
	at com.google.cloud.tools.intellij.appengine.java.ultimate.server.run.AppEngineLocalServerUltimateConfigurationType.getConfigurationFactories(AppEngineLocalServerUltimateConfigurationType.java:73)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1011)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:994)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:204)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:60)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:43)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:64)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:177)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:214)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl$loadSchemes$isLoadOnlyFromProvider$2.invoke(SchemeManagerImpl.kt:42)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:48)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:212)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:273)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:792)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:68)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:441)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.reloadState(ComponentStoreImpl.kt:569)
	at com.intellij.execution.impl.RunManagerImpl$addExtensionPointListeners$1.extensionAdded(RunManagerImpl.kt:708)
	at com.intellij.execution.impl.RunManagerImpl$addExtensionPointListeners$1.extensionAdded(RunManagerImpl.kt:705)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.notifyListeners(ExtensionPointImpl.java:785)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.lambda$registerExtensions$17(ExtensionPointImpl.java:985)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$1.run(DynamicPlugins.kt:819)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:807)
	at com.intellij.ide.plugins.DynamicPlugins.access$loadPlugin(DynamicPlugins.kt:100)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:121)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugins$1.invoke(DynamicPlugins.kt:100)
	at com.intellij.ide.plugins.DynamicPlugins.updateDescriptorsWithoutRestart(DynamicPlugins.kt:165)
```

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4480)
