### ISSUE TITLE
Assertion error on MavenUtils#isMavenIdInDependencyList

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2980]
Plugin 21.7.1
Windows 10
IDEA 2021.2
https://primes-crash.corp.google.com/product/717949/report/1000001168045089015

```
java.lang.AssertionError: Calling methods on invalid value
	at com.intellij.util.xml.impl.StableInvocationHandler.invoke(StableInvocationHandler.java:93)
	at org.jetbrains.idea.maven.dom.model.MavenDomDependency$$EnhancerByJetBrainsMainCglib$$f722dc07.getGroupId(<generated>)
	at com.google.cloud.tools.intellij.cloudapis.maven.MavenUtils.lambda$isMavenIdInDependencyList$0(MavenUtils.java:74)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.google.cloud.tools.intellij.cloudapis.maven.MavenUtils.isMavenIdInDependencyList(MavenUtils.java:71)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.lambda$isManagedDependencyInModule$6(CloudLibraryMavenProjectState.java:254)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.isManagedDependencyInModule(CloudLibraryMavenProjectState.java:251)
	at com.google.cloud.tools.intellij.cloudapis.maven.CloudLibraryMavenProjectState.lambda$loadManagedLibraries$0(CloudLibraryMavenProjectState.java:156)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
```

**Comment by etanshaul** [comment]
clone of https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4481# (forgot to create it on the public repo first).

**Comment by ivanporty** [comment]
https://primes-crash.corp.google.com/product/717949/report/1000001173116824850

**Comment by ivanporty** [comment]
Closing since it doesn't happen anymore, will reopen in case of reoccurrence
