### ISSUE TITLE
"No such file or directory" in WelcomeScreenFileProvider.createEditor

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-intellij#2981]
Plugin 21.7.1
IntelliJ IDEA 2021.2
Linux
https://primes-crash.corp.google.com/product/717949/report/1000001167707835754

```
java.lang.Throwable: /~path~/jbr/lib/libjcef.so: libatk-1.0.so.0: cannot open shared object file: No such file or directory
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.ui.jcef.JBCefApp.<init>(JBCefApp.java:85)
	at com.intellij.ui.jcef.JBCefApp$Holder.init(JBCefApp.java:262)
	at com.intellij.ui.jcef.JBCefApp$Holder.<clinit>(JBCefApp.java:245)
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:227)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:142)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:178)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:147)
	at com.google.cloud.tools.intellij.welcome.WelcomeScreen.getBrowser(WelcomeScreen.kt:71)
	at com.google.cloud.tools.intellij.welcome.WelcomeScreen.getBrowserComponent(WelcomeScreen.kt:42)
	at com.google.cloud.tools.intellij.welcome.WelcomeScreen.getComponent(WelcomeScreen.kt:36)
	at com.google.cloud.tools.intellij.startup.welcome.WelcomeScreenFileProvider.createEditor(WelcomeScreenFileProvider.java:45)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:997)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:969)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1786)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:965)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:63)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:891)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:890)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:731)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1269)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1263)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1239)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:222)
	at com.google.cloud.tools.intellij.startup.StartupScreenLauncher.displayScreen(StartupScreenLauncher.java:112)
	at com.google.cloud.tools.intellij.startup.StartupScreenLauncher.displayWelcomeScreen(StartupScreenLauncher.java:95)
	at com.google.cloud.tools.intellij.startup.StartupScreenLauncher.lambda$runActivity$0(StartupScreenLauncher.java:75)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
```

**Comment by etanshaul** [comment]
@grmoon I'm not sure if this was address / encountered already?

**Comment by etanshaul** [comment]
Kamino cloned this issue to [GoogleCloudPlatform/cloud-code-intellij-internal](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/issues/4482)
