### ISSUE TITLE
java.lang.IllegalStateException: @NotNull method 

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2992]
PyCharm 2021.2.1
Mac OS X
Cloud Code 21.9.2

```
java.lang.IllegalStateException: @NotNull method com/intellij/psi/impl/source/codeStyle/CodeStyleSchemeImpl.getCodeStyleSettings must not return null
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.$$$reportNull$$$0(CodeStyleSchemeImpl.java)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleSchemeImpl.getCodeStyleSettings(CodeStyleSchemeImpl.java:82)
	at com.intellij.psi.codeStyle.CodeStyleSettingsManager.getCurrentSettings(CodeStyleSettingsManager.java:220)
	at com.intellij.application.options.CodeStyle.getSettings(CodeStyle.java:57)
	at org.editorconfig.configmanagement.ConfigEncodingManager.getEncoding(ConfigEncodingManager.java:48)
	at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.getEncoding(EncodingProjectManagerImpl.java:189)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.getEncoding(EncodingManagerImpl.java:242)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.getDefaultCharsetFromEncodingManager(LoadTextUtil.java:271)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.guessFromContent(LoadTextUtil.java:329)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectHardCharset(LoadTextUtil.java:249)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectInternalCharsetAndSetBOM(LoadTextUtil.java:281)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.detectCharsetAndSetBOM(LoadTextUtil.java:265)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.lambda$contentsToByteArray$0(VirtualFileImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:180)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:137)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl.contentsToByteArray(VirtualFileImpl.java:118)
	at com.intellij.openapi.vfs.VfsUtilCore.loadBytes(VfsUtilCore.java:384)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.computeCharset(VirtualFileSystemEntry.java:463)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getCharset(VirtualFileSystemEntry.java:445)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:376)
	at com.intellij.openapi.vfs.VfsUtilCore.loadText(VfsUtilCore.java:372)
	at com.intellij.javascript.nodejs.PackageJsonData.loadText(PackageJsonData.java:449)
	at com.intellij.javascript.nodejs.PackageJsonData.doParse(PackageJsonData.java:431)
	at com.intellij.javascript.nodejs.PackageJsonData.lambda$getOrCreate$16(PackageJsonData.java:412)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.javascript.nodejs.PackageJsonData.getOrCreate(PackageJsonData.java:402)
	at com.intellij.javascript.nodejs.PackageJsonData.lambda$getOrCreateWithPreferredProject$15(PackageJsonData.java:395)
	at com.intellij.openapi.project.ProjectLocator.computeWithPreferredProject(ProjectLocator.java:61)
	at com.intellij.javascript.nodejs.PackageJsonData.getOrCreateWithPreferredProject(PackageJsonData.java:395)
	at com.intellij.javascript.nodejs.library.NodeModulesLibrariesSnapshot$Workspace.getPackageJsonData(NodeModulesLibrariesSnapshot.java:230)
	at com.intellij.javascript.nodejs.library.NodeModulesLibrariesSnapshot$Workspace.getWorkspaceMatchers(NodeModulesLibrariesSnapshot.java:216)
	at com.intellij.javascript.nodejs.library.NodeModulesLibrariesSnapshot$Workspace.matchesChildWorkspace(NodeModulesLibrariesSnapshot.java:240)
	at com.intellij.javascript.nodejs.library.NodeModulesLibrariesSnapshot.lambda$new$1(NodeModulesLibrariesSnapshot.java:71)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:854)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.intellij.javascript.nodejs.library.NodeModulesLibrariesSnapshot.<init>(NodeModulesLibrariesSnapshot.java:36)
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.getOrCreateSnapshot(NodeModulesDirectoryManager.java:388)
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.getNodeModulesDirectories(NodeModulesDirectoryManager.java:253)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.computeRoots(NodeModulesSyntheticLibraryProvider.java:24)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.lambda$getAdditionalProjectLibraries$0(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:43)
	at com.intellij.javascript.nodejs.library.NodeModulesDirectoryManager.computeFileIndexExtensionPreventingRecursion(NodeModulesDirectoryManager.java:205)
	at com.intellij.javascript.nodejs.library.NodeModulesSyntheticLibraryProvider.getAdditionalProjectLibraries(NodeModulesSyntheticLibraryProvider.java:18)
	at com.intellij.openapi.roots.impl.RootIndex.buildRootInfo(RootIndex.java:265)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:72)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:56)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:176)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getRootIndex(DirectoryIndexImpl.java:159)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:186)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:96)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getInfoForFileOrDirectory(ProjectFileIndexImpl.java:27)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:196)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isInContent(ProjectFileIndexFacade.java:30)
	at com.jetbrains.python.psi.search.PyProjectScopeBuilder$2.contains(PyProjectScopeBuilder.java:59)
	at com.intellij.psi.search.scope.NonProjectFilesScope.containsImpl(NonProjectFilesScope.java:36)
	at com.intellij.psi.search.scope.NonProjectFilesScope$1.contains(NonProjectFilesScope.java:26)
	at com.intellij.psi.search.scope.packageSet.FilteredPackageSet.contains(FilteredPackageSet.java:22)
	at com.intellij.ui.tabs.FileColorsModel.findConfiguration(FileColorsModel.java:239)
	at com.intellij.ui.tabs.FileColorsModel.getColor(FileColorsModel.java:210)
	at com.intellij.ui.tabs.FileColorManagerImpl.getFileColor(FileColorManagerImpl.java:157)
	at com.intellij.ui.tabs.EditorTabColorProviderImpl.getProjectViewColor(EditorTabColorProviderImpl.java:31)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getFileBackgroundColor(EditorTabPresentationUtil.java:54)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getFileBackgroundColor(VfsPresentationUtil.java:44)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNode.getBackgroundColorFor(ChangesBrowserNode.java:353)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNode.getBackgroundColor(ChangesBrowserNode.java:336)
	at com.intellij.openapi.vcs.changes.ui.ChangesTree.getFileColorForPath(ChangesTree.java:735)
	at com.intellij.ui.treeStructure.Tree.paintFileColorGutter(Tree.java:342)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:327)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:244)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:947)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$7(ProgressWindow.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:820)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:225)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$execFromEDT$6(ProgressRunner.java:311)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
	at com.intellij.openapi.progress.impl.ProgressRunner.execFromEDT(ProgressRunner.java:308)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:258)
	at com.intellij.openapi.progress.impl.ProgressRunner.submitAndGet(ProgressRunner.java:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:425)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:88)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:275)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.findSkaffoldFiles(SkaffoldFileService.kt:113)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector.showPromptForSkaffoldConfigurations(SkaffoldConfigurationDetector.kt:152)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector.showPromptForSkaffoldConfigurations$default(SkaffoldConfigurationDetector.kt:140)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldConfigurationDetector.onProjectOpened$lambda-0(SkaffoldConfigurationDetector.kt:82)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:401)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:393)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	```

**Comment by gennadiycivil** [comment]
Obsolete
