### ISSUE TITLE
PluginException com.google.cloud.tools.intellij.cloud.sdk.CloudSdkVersionNotifier duplicated

### ISSUE THREAD

**Issue by emmanuelbaah** [GoogleCloudPlatform/cloud-code-intellij#2993]
IntelliJ version:2021.2.1
Plugin Version: 21.7.1
OS: Linux
https://primes-crash.corp.google.com/product/717949/report/1000001174746806950
https://primes-crash.corp.google.com/product/717949/report/1000001174746805457

```
com.intellij.diagnostic.PluginException: Key com.google.cloud.tools.intellij.analytics.OnboardingTrackingService duplicated [Plugin: com.google.gct.core]
	at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:492)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250)
	at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.java:317)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:54)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:138)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:246)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:207)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.getProject(FlatWelcomeFrame.java:516)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.tryGuessFocusedProject(BackendBePopupFactory.kt:52)
	at com.jetbrains.rdserver.ui.popup.bePopups.impl.BackendBePopupFactory.createComponentPopupBuilder(BackendBePopupFactory.kt:124)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:389)
	at com.intellij.ide.HelpTooltip.initPopupBuilder(HelpTooltip.java:395)
	at com.intellij.ide.HelpTooltipManager.showTooltip(HelpTooltipManager.java:20)
	at com.intellij.ide.IdeTooltipManager.showTooltipForEvent(IdeTooltipManager.java:263)
	at com.intellij.ide.IdeTooltipManager.showForComponent(IdeTooltipManager.java:243)
	at com.intellij.ide.IdeTooltipManager.maybeShowFor(IdeTooltipManager.java:202)
	at com.intellij.ide.IdeTooltipManager.eventDispatched(IdeTooltipManager.java:125)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2199)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2091)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2090)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2047)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4933)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4698)
	at java.desktop/java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4676)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4527)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:816)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by etanshaul** [comment]
a similar stacktrace from very likely the same root cause:

```
Key com.google.cloud.tools.intellij.cloud.sdk.CloudSdkVersionNotifier duplicated [Plugin: com.google.gct.core]
error.stacktrace
com.intellij.diagnostic.PluginException: Key com.google.cloud.tools.intellij.cloud.sdk.CloudSdkVersionNotifier duplicated [Plugin: com.google.gct.core]
	at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:488)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:252)
	at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
	at com.intellij.ide.plugins.DynamicPluginsKt.loadModule(DynamicPlugins.kt:1040)
	at com.intellij.ide.plugins.DynamicPluginsKt.access$loadModule(DynamicPlugins.kt:1)
	at com.intellij.ide.plugins.DynamicPlugins$loadPlugin$2.run(DynamicPlugins.kt:832)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:828)
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:808)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:400)
	at com.intellij.ide.plugins.PluginInstaller.installAndLoadDynamicPlugin(PluginInstaller.java:378)
	at com.intellij.ide.plugins.PluginManagerMain$1.lambda$run$0(PluginManagerMain.java:95)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
```

**Comment by peterlin741** [comment]
This is related to compatibility issues from updating to a dynamic plugin. Our team is still investigating.
