### ISSUE TITLE
java.lang.IllegalArgumentException: Missing extension point: com.intellij.remoteServer.debug.runConfigurationAdapter in container Application

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-intellij#2994]
https://primes-crash.corp.google.com/product/717949/report/1000001175601889239

Cloud Code 21.9.2
CLion 2021.2.2
Linux

```
java.lang.IllegalArgumentException: Missing extension point: com.intellij.remoteServer.debug.runConfigurationAdapter in container Application (containerState=COMPONENT_CREATED) 
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:252)
	at com.intellij.openapi.extensions.BaseExtensionPointName.getPointImpl(BaseExtensionPointName.java:28)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.java:39)
	at com.intellij.docker.remoteDebug.RemoteServerRequestAdapterFactory.findAdapterFactory(RemoteServerRequestAdapterFactory.java:64)
	at com.intellij.docker.debug.DockerBeforeRunTaskProvider.createTask(DockerBeforeRunTaskProvider.java:92)
	at com.intellij.docker.debug.DockerBeforeRunTaskProvider.createTask(DockerBeforeRunTaskProvider.java:31)
	at com.intellij.execution.impl.BeforeRunTaskHelperKt.getHardcodedBeforeRunTasks(BeforeRunTaskHelper.kt:36)
	at com.intellij.execution.impl.RunManagerImpl.createTemplateSettings$intellij_platform_execution_impl(RunManagerImpl.kt:341)
	at com.intellij.execution.impl.RunManagerImpl.getConfigurationTemplate(RunManagerImpl.kt:327)
	at com.intellij.execution.impl.RunManagerImpl.createConfiguration(RunManagerImpl.kt:252)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldRunConfigurationManager.createRunConfigurationFromSettings(SkaffoldRunConfigurationManager.kt:137)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldRunConfigurationManager.addSkaffoldRunConfiguration(SkaffoldRunConfigurationManager.kt:74)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.SkaffoldRunConfigurationManager.addSkaffoldRunConfiguration$default(SkaffoldRunConfigurationManager.kt:68)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.CreateSkaffoldConfigurationsAction.actionPerformed(CreateSkaffoldConfigurationsAction.kt:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.notification.Notification.fire(Notification.java:194)
	at com.intellij.notification.impl.NotificationsManagerImpl.lambda$createActionPanel$9(NotificationsManagerImpl.java:733)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:177)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:363)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	```

**Comment by gennadiycivil** [comment]
Obsolete
