### ISSUE TITLE
ID "LspStateAction" is already taken by action "Show LSP state (null)". Action "Show LSP state (null)" cannot use the same ID

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-intellij#2997]
```
java.lang.Throwable: ID "LspStateAction" is already taken by action "Show LSP state (null)". Action "Show LSP state (null)" cannot use the same ID
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:360)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:349)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1296)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1239)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1303)
	at com.google.cloud.tools.intellij.languageclient.LspStateDeveloperAction$Companion.registerIfEnabled(LspStateDeveloperAction.kt:53)
	at com.google.cloud.tools.intellij.languageclient.LanguageServerProjectStateService$setupServer$2.invokeSuspend(LanguageServerProjectStateService.kt:133)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Nightly build, might be a flake error. Need pattern and release version to confirm.

**Comment by matthewmichihara** [comment]
I'm just going to delete this debug action unless anyone feels strongly that we should keep it around.
