### ISSUE TITLE
Application restart in debug mode leads to stuck debug configuration/state

### ISSUE THREAD

**Issue by sbaier1** [GoogleCloudPlatform/cloud-code-intellij#3015]
### Context

What i'm trying to do: i'm running a java, micronaut application. I am building it with jib and instrumented it with micronaut's hot-restart (note: this is no hot-reload at runtime, but a complete restart of the process) so it will restart on code changes.

This works fine for normal running, but when i run it in debug with hot-restart, once the container has performed a restart and is ready for debugging again, the debug run configuration breaks and is unable to re-attach. This is accompanied by an `unknown error` in the IDE. I attached the corresponding exception trace below.

However, when i create a run configuration with the same parameters as the one generated by Cloud Code in IntellIJ's regular JVM debugging plugin, i can still attach to the debugger, so the port-forward/debug instrumentation itself doesn't seem to be the problem.

### Expected Behavior

I can reattach the debugger when it gets disconnected in a `skaffold debug` session by simply re-starting the debug configuration that skaffold generates.

### Actual Behavior

It is not possible to re-attach a debugger after being forcibly disconnected (for example because the application has restarted).

### Additional Information

IDE type (e.g. IntelliJ, Pycharm): IntelliJ
IDE version: 2021.2.3
Cloud Code version (Settings > Plugins > Cloud Code): 21.10.1

#### Deployment patches i applied

```yaml
piVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  selector:
    matchLabels:
      app: my-api
  replicas: 1
  template:
    metadata:
      labels:
        app: my-api
      # So skaffold will use my debugging instrumentation instead of overwriting my container cmd/args
      annotations:
        debug.cloud.google.com/config: '{"api":{"artifact":"my-repo/my-api-image","runtime":"jvm","ports":{"jdwp":5005}}}'
      containers:
        - name: api
          ports:
            # Add debug port to always be able to attach to it
            - containerPort: 5005
              name: jdwp
              protocol: TCP
          env:
            # To enable micronaut's hot restart feature on class change
            - name: MICRONAUT_IO_WATCH_ENABLED
              value: "true"
            - name: MICRONAUT_IO_WATCH_RESTART
              value: "true"
            - name: MICRONAUT_IO_WATCH_PATHS
              value: "/app/classes"
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"
          # Very dumb/basic instrumentation for micronaut hot-restart so we don't get pod-restarts
          command:
            - /bin/bash
            - -c
          args:
            #language=bash
            - |
              # Restart without killing the pod when the API self-restarts due to hot-reload.
              while true; do
                echo  "Starting API"
                # Original entrypoint
                java -cp @/app/jib-classpath-file com.example.ApiMain
                RET_CODE=$?
                if [[ "${RET_CODE}" != "0" ]]; then
                  echo "Exit code ${RET_CODE} != 0, restarting container"
                  exit "${RET_CODE}"
                fi
              done
```

#### corresponding idea.log error

```java
2021-10-26 15:39:25,992 [26335319]   INFO - xecution.runners.ExecutionUtil - Error running 'Debug(5008): api':<br>Unknown error 
java.lang.NullPointerException
	at com.intellij.debugger.engine.RemoteDebugProcessHandler.startNotify(RemoteDebugProcessHandler.java:41)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2$1.run(ExecutionManagerImpl.kt:253)
	at com.intellij.ui.AppUIUtil.invokeLaterIfProjectAlive(AppUIUtil.java:203)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:234)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1$2.accept(ExecutionManagerImpl.kt:70)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:349)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:318)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:233)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)

```

**Comment by emmanuelbaah** [comment]
Briefly reopening just to let you know that the feature is now available in the [Insider Build](https://github.com/GoogleCloudPlatform/cloud-code-intellij#insider-builds)!
