### ISSUE TITLE
Plugin Exception at SkaffoldSchemaUpgradeInspection

### ISSUE THREAD

**Issue by emmanuelbaah** [GoogleCloudPlatform/cloud-code-intellij#3031]
- IDE type (e.g. IntelliJ, Pycharm): IntelliJ
- IDE version: 2021.2.3
- Cloud Code version (Settings > Plugins > Cloud Code): 21.10.1
- Operating System:Mac OS X

```
com.intellij.diagnostic.PluginException: com.google.cloud.tools.intellij.kubernetes.skaffold.inspections.SkaffoldSchemaUpgradeInspection [Plugin: com.google.gct.core]
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:895)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.createInstance(CustomLoadingExtensionPointBean.java:29)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:206)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.<init>(InspectionToolWrapper.java:64)
	at com.intellij.codeInspection.ex.LocalInspectionToolWrapper.<init>(LocalInspectionToolWrapper.java:22)
	at com.intellij.codeInspection.ex.LocalInspectionToolWrapper.createCopy(LocalInspectionToolWrapper.java:27)
	at com.intellij.codeInspection.ex.LocalInspectionToolWrapper.createCopy(LocalInspectionToolWrapper.java:11)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.copyToolSettings(InspectionProfileImpl.java:104)
	at com.intellij.codeInspection.ex.InspectionProfileModifiableModel.copyToolsConfigurations(InspectionProfileModifiableModel.kt:44)
	at com.intellij.codeInspection.ex.InspectionProfileModifiableModel.copyToolsConfigurations(InspectionProfileModifiableModel.kt:34)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.initialize(InspectionProfileImpl.java:516)
	at com.intellij.codeInspection.ex.NewInspectionProfile.initInspectionTools(InspectionProfile.kt:113)
	at com.intellij.codeInspection.ex.InspectionProfileImpl.getToolsOrNull(InspectionProfileImpl.java:867)
	at com.intellij.codeInspection.ex.NewInspectionProfile.getTools(InspectionProfile.kt:101)
	at com.intellij.codeInspection.ex.InspectionProfileModifiableModel.disableTool(InspectionProfileModifiableModel.kt:123)
	at com.intellij.codeInspection.ex.DisableInspectionToolAction.lambda$applyFix$0(DisableInspectionToolAction.java:68)
	at com.intellij.codeInspection.ex.InspectionProfileModifiableModelKt.modifyAndCommitProjectProfile(InspectionProfileModifiableModel.kt:130)
	at com.intellij.codeInspection.ex.DisableInspectionToolAction.applyFix(DisableInspectionToolAction.java:68)
	at com.intellij.codeInspection.IntentionAndQuickFixAction.invoke(IntentionAndQuickFixAction.java:54)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.lambda$invoke$0(IntentionActionWithTextCaching.java:209)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:152)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:209)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.invokeIntention(ShowIntentionActionsHandler.java:266)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$chooseActionAndInvoke$3(ShowIntentionActionsHandler.java:239)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseActionAndInvoke(ShowIntentionActionsHandler.java:238)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.chooseActionAndInvoke(IntentionListStep.java:134)
	at com.intellij.codeInsight.intention.impl.IntentionListStep$1.chooseActionAndInvoke(IntentionListStep.java:162)
	at com.intellij.codeInsight.intention.impl.IntentionListStep.lambda$applyAction$3(IntentionListStep.java:126)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1503)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:186)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:175)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1500)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:163)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:337)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:136)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:166)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:155)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:143)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:266)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:268)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:444)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:416)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:367)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:281)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:354)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:101)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.tools.intellij.kubernetes.skaffold.inspections.SkaffoldSchemaUpgradeInspection
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:227)
	at com.intellij.util.lang.PathClassLoader.findClass(PathClassLoader.java:65)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1492)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:887)
	... 69 more
```

Seems very similar to https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3026

**Comment by peterlin741** [comment]
closing this issue since `SkaffoldSchemaUpgradeInspection` was removed in https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/5005

the other open issue is still relevant: https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues/3026

**Comment by peterlin741** [comment]
The above class `SkaffoldSchemaUpgradeInspection` has been removed
