### ISSUE TITLE
 java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by emmanuelbaah** [GoogleCloudPlatform/cloud-code-intellij#3047]
- IDE type (e.g. IntelliJ, Pycharm): IntelliJ IDEA
- IDE version: 2021.2
- Cloud Code version (Settings > Plugins > Cloud Code): 21.11.1
- Operating System: Mac OS X

```
No space left on device
error.stacktrace
java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
	at java.base/java.io.DataOutputStream.writeLong(DataOutputStream.java:224)
	at com.intellij.util.io.ResizeableMappedFile.writeLength(ResizeableMappedFile.java:146)
	at com.intellij.util.io.ResizeableMappedFile.ensureLengthWritten(ResizeableMappedFile.java:167)
	at com.intellij.util.io.ResizeableMappedFile.force(ResizeableMappedFile.java:161)
	at com.intellij.util.io.keyStorage.AppendableStorageBackedByResizableMappedFile.force(AppendableStorageBackedByResizableMappedFile.java:50)
	at com.intellij.util.indexing.impl.storage.IntLog$doForce$1.invoke(IntLog.kt:167)
	at com.intellij.util.indexing.impl.storage.IntLog$doForce$1.invoke(IntLog.kt:42)
	at com.intellij.util.indexing.impl.storage.IntLog.withLock(IntLog.kt:180)
	at com.intellij.util.indexing.impl.storage.IntLog.doForce(IntLog.kt:167)
	at com.intellij.util.indexing.impl.storage.IntLog.processEntries(IntLog.kt:63)
	at com.intellij.psi.search.LogFileTypeIndex$LogBasedIntIntIndex.getFileIds(LogFileTypeIndex.java:406)
	at com.intellij.psi.search.LogFileTypeIndex.getData(LogFileTypeIndex.java:187)
	at com.intellij.psi.search.LogFileTypeIndex.getData(LogFileTypeIndex.java:41)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$10(FileBasedIndexEx.java:350)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$5(FileBasedIndexEx.java:248)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:234)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$6(FileBasedIndexEx.java:248)
	at com.intellij.util.indexing.diagnostic.IndexAccessValidator.validate(IndexAccessValidator.java:42)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:248)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:349)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:318)
	at com.intellij.util.indexing.FileBasedIndexEx.getContainingFiles(FileBasedIndexEx.java:200)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:42)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.findSkaffoldFiles$lambda-5$lambda-4(SkaffoldFileService.kt:99)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldFileService.findSkaffoldFiles$lambda-5(SkaffoldFileService.kt:97)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:279)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$8(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by emmanuelbaah** [comment]
closing as this is an issue the IDE should be handling
