### ISSUE TITLE
Invalid Data: Skaffold configuration file doesn't exist or is invalid.

### ISSUE THREAD

**Issue by MSworlds** [GoogleCloudPlatform/cloud-code-intellij#3079]
### Expected Behavior
 Develop on Kubernetes without warning when saving the configuration，Invalid Data: Skaffold configuration file doesn't exist or is invalid.

### Actual Behavior
![1652428187(1)](https://user-images.githubusercontent.com/33744465/168236739-d89af690-5f99-4602-9155-7ed1b40f8d84.png)

idea log:
```
2022-05-13 15:18:39,871 [  94451]   INFO - ernetes.kpt.KptExecutorService - Error parsing kpt version 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "kpt": CreateProcess error=2, 系统找不到指定的文件。
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:391)
	at com.google.cloud.tools.intellij.util.CommandExecutor.run(CommandExecutor.kt:91)
	at com.google.cloud.tools.intellij.util.CommandExecutor.run$default(CommandExecutor.kt:77)
	at com.google.cloud.tools.intellij.kubernetes.kpt.KptExecutorService.createProcess(KptExecutorService.kt:141)
	at com.google.cloud.tools.intellij.kubernetes.kpt.KptExecutorService.executeKpt(KptExecutorService.kt:109)
	at com.google.cloud.tools.intellij.kubernetes.kpt.KptExecutorService.getKptVersion(KptExecutorService.kt:87)
	at com.google.cloud.tools.intellij.kubernetes.kpt.KptExecutorService.getManagedKptVersion(KptExecutorService.kt:75)
	at com.google.cloud.tools.intellij.configurables.DeploymentToolsDependenciesPanel$setManagedDependencyVersions$1$kptVersion$1.invokeSuspend(DeploymentToolsDependenciesPanel.kt:352)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "kpt": CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:464)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:381)
	... 13 more
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 16 more
2022-05-13 15:18:44,066 [  98646]   INFO - red.download.SharedIndexLookup - Selected pre-built shared index SharedIndexResult(request='MavenLibraryIndexRequest(MavenPackageId(com.fasterxml.jackson.core:jackson-core:2.11.3))', url='https://index-cdn.jetbrains.com/v2/data/mvn/com.fasterxml.jackson.core:jackson-core:2.13.0/com_fasterxml_jackson_core_jackson_core_2_13_0-linux-f4b9c13e249f128929a9469f30bce308e5790b4a59174e5ba8ab9ca746259a54.ijx.xz', weakHash=603370864728, weakBaseVersionHash=1645f8fc6d06, sha256='f4b9c13e249f128929a9469f30bce308e5790b4a59174e5ba8ab9ca746259a54') from https://index-cdn.jetbrains.com/v2/mvn/major-version/com.fasterxml.jackson.core:jackson-core:2 for MavenLibraryIndexRequest(MavenPackageId(com.fasterxml.jackson.core:jackson-core:2.11.3)) 
2022-05-13 15:18:47,212 [ 101792]   WARN - ij.codeInspection.InspectionEP - com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineDeprecatedRuntimeInspection 
2022-05-13 15:18:47,232 [ 101812]   WARN - ij.codeInspection.InspectionEP - com.google.cloud.tools.intellij.appengine.java.inspections.AppEngineDeprecatedRuntimeInspection 
2022-05-13 15:18:55,496 [ 110076]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Dependencies' id=com.google.cloud.tools.intellij.configurables.DependenciesConfigurable 
2022-05-13 15:18:57,265 [ 111845]   INFO - .deployment.AsyncDevicesGetter - adb not found 
2022-05-13 15:18:59,868 [ 114448]   WARN - rofile.SkaffoldProfileComboBox - skaffold file is null -- updating profile combobox with empty list. 
2022-05-13 15:19:03,474 [ 118054]   WARN - RunConfigurationSettingsEditor - There was an error detecting build environment compatibility. 
java.lang.Exception: Unknown skaffold file.
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:861)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.access$getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:115)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor$calculateCompatibility$2$buildEnvironmentDeferred$1.invokeSuspend(SkaffoldRunConfigurationSettingsEditor.kt:912)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Additional Information

- IDE type :IntelliJ
- IDE version:  2021.2.3(Ultimate Edition)
- Cloud Code version (Settings > Plugins > Cloud Code): 22.4.2-212
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: yes
  - Version of the Cloud SDK:381.0.0
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 1.37.2
- Operating System: windows10

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ruomengz** [comment]
Thank you for reporting this, the stack trace is very helpful!
We are currently investigating and will keep you updated.

**Comment by LeovR** [comment]
I have a similar issue on windows where the skaffold.yaml isn't detected or parsed correctly.

On startup this is logged:

```
2022-07-06 07:12:09,904 [1356532]   WARN - #c.g.c.t.i.k.s.r.u.p.SkaffoldProfileComboBox - skaffold file is null -- updating profile combobox with empty list.
2022-07-06 07:12:10,325 [1356953]   WARN - #c.g.c.t.i.k.s.r.u.SkaffoldRunConfigurationSettingsEditor - There was an error detecting build environment compatibility.
java.lang.Exception: Unknown skaffold file.
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:858)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.access$getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:115)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor$calculateCompatibility$2$buildEnvironmentDeferred$1.invokeSuspend(SkaffoldRunConfigurationSettingsEditor.kt:909)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-07-06 07:12:13,311 [1359939]   WARN - #c.g.c.t.i.k.s.r.u.b.SkaffoldBuildPanel - Failed to read artifacts from skaffold yaml file
java.util.NoSuchElementException: No document is available.
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:133)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:494)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:136)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.build.SkaffoldBuildPanel$updateArtifactSettings$1$skaffoldConfigurationList$1.invokeSuspend(SkaffoldBuildPanel.kt:464)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-07-06 07:12:13,313 [1359941]   WARN - #c.g.c.t.i.k.s.r.u.SkaffoldRunConfigurationSettingsEditor - There was an error detecting build environment compatibility.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:252)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:97)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:134)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:494)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:136)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:862)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.access$getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:115)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor$calculateCompatibility$2$buildEnvironmentDeferred$1.invokeSuspend(SkaffoldRunConfigurationSettingsEditor.kt:909)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```` 

and also this:
```
2022-07-06 07:13:59,304 [1465932]   WARN - #c.g.c.t.i.k.s.r.SkaffoldCommandLineState - Failed to execute process Process[pid=20352, exitValue=1]. Exit code 1.
2022-07-06 07:13:59,306 [1465934]   WARN - #c.g.c.t.i.k.s.e.SkaffoldEventHandler - Skaffold event API stream received termination error
io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-07-06 07:13:59,306 [1465934]   WARN - #c.g.c.t.i.k.s.e.SkaffoldEventHandler - Skaffold v2 API stream received termination error
io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
2022-07-06 07:15:36,181 [1562809]   WARN - #c.g.c.t.i.k.s.r.u.p.SkaffoldProfileComboBox - skaffold file is null -- updating profile combobox with empty list.
2022-07-06 07:15:39,646 [1566274]   WARN - #c.g.c.t.i.k.s.r.u.b.SkaffoldBuildPanel - Failed to read artifacts from skaffold yaml file
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:536)
	at org.yaml.snakeyaml.util.ArrayStack.pop(ArrayStack.java:32)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:78)
	at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:123)
	at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:489)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:136)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.build.SkaffoldBuildPanel$updateArtifactSettings$1$skaffoldConfigurationList$1.invokeSuspend(SkaffoldBuildPanel.kt:464)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

And when I try to change the run configuration and open the "Build/Deploy" tab I can see also the following error:

```
2022-07-06 07:34:49,805 [2716433]   WARN - #c.g.c.t.i.k.s.r.u.p.SkaffoldProfileComboBox - skaffold file is null -- updating profile combobox with empty list.
2022-07-06 07:34:51,698 [2718326]   WARN - #c.g.c.t.i.k.s.r.u.b.SkaffoldBuildPanel - Failed to read artifacts from skaffold yaml file
while parsing a block mapping
 in 'reader', line 1, column 11:
    apiVersion: skaffold/v2beta29
              ^
expected <block end>, but found '<scalar>'
 in 'reader', line 1, column 13:
    apiVersion: skaffold/v2beta29
                ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingFirstKey.produce(ParserImpl.java:552)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:134)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:494)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:136)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.build.SkaffoldBuildPanel$updateArtifactSettings$1$skaffoldConfigurationList$1.invokeSuspend(SkaffoldBuildPanel.kt:464)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-07-06 07:34:51,700 [2718328]   WARN - #c.g.c.t.i.k.s.r.u.SkaffoldRunConfigurationSettingsEditor - There was an error detecting build environment compatibility.
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:536)
	at org.yaml.snakeyaml.util.ArrayStack.pop(ArrayStack.java:32)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:78)
	at org.yaml.snakeyaml.constructor.BaseConstructor.checkData(BaseConstructor.java:123)
	at org.yaml.snakeyaml.Yaml$1.hasNext(Yaml.java:489)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.SkaffoldYamlLoader.loadEffective(SkaffoldYamlLoader.kt:136)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:862)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor.access$getSelectedBuildEnvironment(SkaffoldRunConfigurationSettingsEditor.kt:115)
	at com.google.cloud.tools.intellij.kubernetes.skaffold.run.ui.SkaffoldRunConfigurationSettingsEditor$calculateCompatibility$2$buildEnvironmentDeferred$1.invokeSuspend(SkaffoldRunConfigurationSettingsEditor.kt:909)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by iosifnicolae2** [comment]
I had the same problem on MacOS.

**Comment by evgenimi** [comment]
I have the same issue on MacOS with PyCharm 2023.1.3 and 23.6.3-api-version-222 Cloud Code plugin

**Comment by sharabhshukla** [comment]
This problem occurs when one creates a skaffold.yaml file by running skaffold init and then pycharm run config throws an error, saying the file is valid. Where as if you copy from one of the example, then it works, but also when you see the file created by running skaffold init vs example, its different

**Comment by ivanporty** [comment]
Thanks @sharabhshukla for the detailed steps. We will try to reproduce and update you with the results.

**Comment by sharabhshukla** [comment]
Intrestingly, Initially I had installed, skaffold using scoop, I am on windows. I removed it and installed skaffold and kubectl using gcloud components. I now find the problem has gone. Now skaffold.yaml generated using, skaffold init readily works with pycharm plugin.
