### ISSUE TITLE
Google Cloud Storage does not populate

### ISSUE THREAD

**Issue by johnkangw** [GoogleCloudPlatform/cloud-code-intellij#3162]
(Please ensure you are running the latest version of Cloud Cloud IntelliJ with _Help > Check for Updates_.)

(screenshots are often helpful)

### Expected Behavior
Google Cloud Storage lists my buckets
### Actual Behavior
Stuck in a spinning circle with resources. 
### Additional Information

![image](https://github.com/GoogleCloudPlatform/cloud-code-intellij/assets/72617548/3c843013-3294-4928-9207-842bdef6d0c2)

PyCharm error:
Unhandled exception in [ANY, StandaloneCoroutine{Cancelling}@79abdc5f, Dispatchers.EDT]
  
  java.lang.IllegalArgumentException: You must specify at least one condition to use object lifecycle management. Please see https://cloud.google.com/storage/docs/lifecycle for details.
at com.google.cloud.storage.BucketInfo$LifecycleRule.<init>(BucketInfo.java:118)
at com.google.cloud.storage.BucketInfo$LifecycleRule.fromPb(BucketInfo.java:222)
at com.google.cloud.storage.BucketInfo$9.apply(BucketInfo.java:1490)
at com.google.cloud.storage.BucketInfo$9.apply(BucketInfo.java:1487)
at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:674)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:53)
at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:146)
at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:284)
at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:252)
at com.google.cloud.storage.BucketInfo$BuilderImpl.setLifecycleRules(BucketInfo.java:911)
at com.google.cloud.storage.BucketInfo.fromPb(BucketInfo.java:1484)
at com.google.cloud.storage.Bucket.fromPb(Bucket.java:1214)
at com.google.cloud.storage.StorageImpl$7.apply(StorageImpl.java:334)
at com.google.cloud.storage.StorageImpl$7.apply(StorageImpl.java:331)
at com.google.common.collect.Iterators$7.transform(Iterators.java:870)
at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:53)
at com.google.cloud.PageImpl$PageIterator.computeNext(PageImpl.java:72)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1295)
at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1328)
at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1319)
at com.google.cloud.tools.intellij.resource.browser.data.OnDemandBucketListResource.loadChildren(OnDemandBucketListResource.kt:22)
at com.google.cloud.tools.intellij.resource.browser.tree.node.CloudResourceGroupNode$refreshNode$1$1$1.invokeSuspend(CloudResourceGroupNode.kt:37)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ANY, StandaloneCoroutine{Cancelled}@79abdc5f, Dispatchers.EDT]

- IDE type (e.g. IntelliJ, Pycharm): PyCharm
- IDE version:Build #PY-232.9559.58, built on August 22, 202
- Cloud Code version (Settings > Plugins > Cloud Code): 23.9.1-api-version-222
- Cloud SDK (Settings > Cloud Code > Cloud SDK)
  - Are you allowing the plugin to manage the Cloud SDK: Not sure
  - Version of the Cloud SDK:
- Skaffold version (If you are using Kubernetes features; Settings > Cloud Code > Kubernetes): 
- Operating System: Windows

_Feel free to deviate from this template as needed, especially if you are submitting a feature request._

**Comment by ivanporty** [comment]
Thank you for the report @johnkangw! To clarify, was it working for you in the previous release (23.9.1)?

**Comment by johnkangw** [comment]
@ivanporty Thanks for the reply! I only started trying it so it has not worked for me.

**Comment by emmanuelbaah** [comment]
@johnkangw The issue has been fixed and released. Please update to `23.9.3-api-version-222` and re-open this if the issue persists!

**Comment by johnkangw** [comment]
@emmanuelbaah It works! Thanks! Also, Big Data Tools is working too for GCS.
