### ISSUE TITLE
Gemini Code completions do not work when running over remote connections

### ISSUE THREAD

**Issue by jshelman** [GoogleCloudPlatform/cloud-code-intellij#3195]
### Expected Behavior

Code completions should work correctly in  remote (host) ide window.

### Actual Behavior

Code completions do not work when running Remote ide thru ssh connection.
Language server logs show a valid response from Gemini aicompanion endpoint, but do not make it to IDE window.

idea.log
2024-04-16 04:59:34,868 [ 121166]   WARN - duet-ai-language-server - Rendering inline completion failed
com.intellij.diagnostic.PluginException: Positive width should be defined for an inline element by import org.springframework.boot.SpringApplication; [Plugin: com.google.gct.core]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.openapi.editor.impl.InlineInlayImpl.doUpdate(InlineInlayImpl.java:75)
	at com.intellij.openapi.editor.impl.InlayImpl.<init>(InlayImpl.java:34)
	at com.intellij.openapi.editor.impl.InlineInlayImpl.<init>(InlineInlayImpl.java:27)
	at com.intellij.openapi.editor.impl.InlayModelImpl.addInlineElement(InlayModelImpl.java:154)
	at com.google.cloud.tools.intellij.languageclient.aicompanion.InlineCompletionResultProvider.renderCompletionTextInInlays(InlineCompletionResultProvider.kt:252)
	at com.google.cloud.tools.intellij.languageclient.aicompanion.InlineCompletionResultProvider.renderInlineCompletionText(InlineCompletionResultProvider.kt:192)
	at com.google.cloud.tools.intellij.languageclient.aicompanion.InlineCompletionResultRenderingService$sendRequestAndRender$1$1.invokeSuspend(InlineCompletionResultRenderingService.kt:170)
...

### Additional Information

- IDE type (e.g. IntelliJ, Pycharm):   Tested with same behavior on both  Intellij (and PyCharm)
- IDE version: 2023.3.4,  2024.1
- Cloud Code version (Settings > Plugins > Cloud Code):  24.4.2-api-version-223

**Comment by ivanporty** [comment]
Thanks for the report @jshelman. Remote environments do no support the mechanism we use to render the completions - we are currently working to change this into a better implementation and will let you know once it's ready.

**Comment by ivanporty** [comment]
With the brand new Gemini implementation since version 24.8.1, completions should work properly in the remote environments. Closing, please re-open if it doesn't work for you.
